from __future__ import annotations

import re
from copy import deepcopy
from dataclasses import dataclass, field
from typing import Any


SOURCE_HANDLE = "source"
FALSE_HANDLE = "false"
DIFY_REF_PATTERN = re.compile(r"\{\{\s*#([A-Za-z0-9_-]+)\.([A-Za-z0-9_.-]+)#\s*\}\}")


@dataclass(frozen=True)
class NormalizationResult:
    payload: dict[str, Any]
    changed: bool
    changes: list[str] = field(default_factory=list)


def normalize_plan_payload(payload: dict[str, Any], *, app_name: str | None = None) -> NormalizationResult:
    data = deepcopy(payload)
    changes: list[str] = []
    if not isinstance(data, dict):
        raise ValueError("plan payload must be a JSON object")

    if app_name and data.get("name") != app_name:
        data["name"] = app_name
        changes.append("set workflow name from request app_name")
    data.setdefault("name", "Generated Workflow")
    data.setdefault("description", "Generated by chat2dify.")

    nodes = data.get("nodes")
    edges = data.get("edges")
    if not isinstance(nodes, list):
        raise ValueError("plan.nodes must be a list")
    if not isinstance(edges, list):
        raise ValueError("plan.edges must be a list")

    for node in nodes:
        if not isinstance(node, dict):
            raise ValueError("plan.nodes items must be objects")
        node.setdefault("title", _default_title(str(node.get("type", ""))))
        node.setdefault("desc", "")
        params = node.get("params")
        if not isinstance(params, dict):
            params = {}
            node["params"] = params

        node_type = node.get("type")
        before = deepcopy(params)
        match node_type:
            case "start":
                node["params"] = _normalize_start_params(params)
            case "llm":
                node["params"] = _normalize_llm_params(params)
            case "code":
                node["params"] = _normalize_code_params(params)
            case "if-else":
                node["params"] = _normalize_if_else_params(params)
            case "end":
                node["params"] = _normalize_end_params(params)
            case "http-request":
                node["params"] = _normalize_http_params(params)
            case "template-transform":
                node["params"] = _normalize_template_params(params)
        if before != node.get("params"):
            changes.append(f"normalized {node.get('id', '<unknown>')} params")

    node_by_id = {str(node.get("id")): node for node in nodes if isinstance(node, dict)}
    edge_positions = _if_else_edge_positions(edges, node_by_id)
    for edge in edges:
        if not isinstance(edge, dict):
            raise ValueError("plan.edges items must be objects")
        edge.setdefault("source_handle", SOURCE_HANDLE)
        edge.setdefault("target_handle", "target")
        source = node_by_id.get(str(edge.get("source")))
        if source and source.get("type") == "if-else":
            old_handle = edge.get("source_handle")
            new_handle = _infer_if_else_source_handle(source, edge, node_by_id, edge_positions)
            if old_handle != new_handle:
                edge["source_handle"] = new_handle
                changes.append(f"normalized if-else edge handle for {edge.get('source')} -> {edge.get('target')}")

    return NormalizationResult(payload=data, changed=bool(changes), changes=changes)


def normalize_template_refs(text: str) -> str:
    return re.sub(
        r"\{\{\s*(?!#)([A-Za-z0-9_-]+)\.([A-Za-z0-9_.-]+)\s*\}\}",
        r"{{#\1.\2#}}",
        text,
    )


def _normalize_start_params(params: dict[str, Any]) -> dict[str, Any]:
    raw_variables = params.get("variables") or params.get("inputs") or []
    variables = []
    for item in raw_variables:
        if not isinstance(item, dict):
            continue
        name = item.get("name") or item.get("variable")
        if not name:
            continue
        variables.append(
            {
                "name": str(name),
                "type": _input_type(str(item.get("type", "paragraph"))),
                "required": bool(item.get("required", True)),
                "label": item.get("label") or str(name),
            }
        )
    if not variables:
        variables.append({"name": "query", "type": "paragraph", "required": True, "label": "Query"})
    return {"variables": variables}


def _normalize_llm_params(params: dict[str, Any]) -> dict[str, Any]:
    result = dict(params)
    result.pop("prompt", None)
    result["system_prompt"] = normalize_template_refs(str(params.get("system_prompt", "")))
    result["user_prompt"] = normalize_template_refs(
        str(params.get("user_prompt") or params.get("prompt") or "{{#start.query#}}")
    )
    result.setdefault("completion_params", {"temperature": 0.7})
    return result


def _normalize_code_params(params: dict[str, Any]) -> dict[str, Any]:
    result = dict(params)
    if "language" in result and "code_language" not in result:
        result["code_language"] = result.pop("language")
    result.setdefault("code", "def main(query: str) -> dict:\n    return {\"result\": query}\n")
    result.setdefault("code_language", "python3")
    result["variables"] = _normalize_variables(result.get("variables", []), result.get("inputs"))
    if not result.get("outputs"):
        result["outputs"] = _infer_code_outputs(str(result["code"]))
    return result


def _normalize_if_else_params(params: dict[str, Any]) -> dict[str, Any]:
    raw_cases = params.get("cases") or []
    cases = []
    for idx, raw_case in enumerate(raw_cases):
        if not isinstance(raw_case, dict):
            continue
        case_id = str(raw_case.get("case_id") or raw_case.get("id") or ("true" if idx == 0 else f"case_{idx + 1}"))
        raw_conditions = raw_case.get("conditions")
        if not raw_conditions and raw_case.get("condition"):
            raw_conditions = [_condition_from_text(str(raw_case["condition"]))]
        conditions = []
        for condition in raw_conditions or []:
            if not isinstance(condition, dict):
                continue
            condition_copy = dict(condition)
            if isinstance(condition_copy.get("variable_selector"), str):
                condition_copy["variable_selector"] = _selector_from_ref(condition_copy["variable_selector"])
            condition_copy.setdefault("comparison_operator", "not empty")
            condition_copy.setdefault("value", "")
            condition_copy.setdefault("varType", "string")
            conditions.append(condition_copy)
        cases.append(
            {
                "case_id": case_id,
                "logical_operator": raw_case.get("logical_operator", "and"),
                "conditions": conditions or [
                    {
                        "variable_selector": params.get("variable_selector", ["start", "query"]),
                        "comparison_operator": "not empty",
                        "value": "",
                        "varType": "string",
                    }
                ],
            }
        )
    if not cases:
        cases.append(
            {
                "case_id": "true",
                "logical_operator": "and",
                "conditions": [
                    {
                        "variable_selector": params.get("variable_selector", ["start", "query"]),
                        "comparison_operator": "not empty",
                        "value": "",
                        "varType": "string",
                    }
                ],
            }
        )
    return {"cases": cases, "else_case": str(params.get("else_case", FALSE_HANDLE))}


def _normalize_end_params(params: dict[str, Any]) -> dict[str, Any]:
    outputs = params.get("outputs") or [{"variable": "answer", "value_selector": ["llm", "text"]}]
    return {"outputs": [_normalize_output(item) for item in outputs if isinstance(item, dict)]}


def _normalize_http_params(params: dict[str, Any]) -> dict[str, Any]:
    result = dict(params)
    result["variables"] = _normalize_variables(result.get("variables", []))
    result["method"] = str(result.get("method", "GET")).upper()
    result["url"] = normalize_template_refs(str(result.get("url", "https://example.com")))
    result["headers"] = _normalize_key_value_text(result.get("headers", ""))
    result["params"] = _normalize_key_value_text(result.get("params", ""))
    body = result.get("body", {"type": "none", "data": []})
    if isinstance(body, dict) and isinstance(body.get("data"), str):
        body = {**body, "data": normalize_template_refs(body["data"])}
    elif body in (None, "", [], {}):
        body = {"type": "none", "data": []}
    result["body"] = body
    if result.get("timeout") is None:
        result.pop("timeout", None)
    if result.get("retry_config") is None:
        result.pop("retry_config", None)
    return result


def _normalize_template_params(params: dict[str, Any]) -> dict[str, Any]:
    template = normalize_template_refs(str(params.get("template", "{{ query }}")))
    variables = _normalize_variables(params.get("variables", []))
    return {
        **params,
        "template": template,
        "variables": _add_template_ref_variables(template, variables),
    }


def _normalize_variables(items: Any, inputs: Any = None) -> list[dict[str, Any]]:
    variables = []
    for item in items or []:
        if not isinstance(item, dict):
            continue
        variable = item.get("variable")
        selector = item.get("value_selector")
        if variable and selector:
            variables.append(_normalize_output({"variable": str(variable), "value_selector": selector}))
    if isinstance(inputs, dict):
        for variable, ref in inputs.items():
            variables.append(_normalize_output({"variable": str(variable), "value_selector": _selector_from_ref(str(ref))}))
    return variables


def _normalize_key_value_text(value: Any) -> str:
    if value in (None, "", [], {}):
        return ""
    if isinstance(value, dict):
        lines = [
            f"{str(key).strip()}:{normalize_template_refs(str(item)).strip()}"
            for key, item in value.items()
            if str(key).strip() and str(item).strip()
        ]
        return "\n".join(lines)
    if isinstance(value, list):
        lines = []
        for item in value:
            if not isinstance(item, dict):
                continue
            key = str(item.get("key", "")).strip()
            raw_value = item.get("value", "")
            item_value = normalize_template_refs(str(raw_value)).strip()
            if key and item_value:
                lines.append(f"{key}:{item_value}")
        return "\n".join(lines)

    text = str(value).strip()
    if text in {"[]", "{}", "null", "None"}:
        return ""
    lines = []
    for line in normalize_template_refs(text).splitlines():
        key, separator, raw_value = line.partition(":")
        key = key.strip()
        item_value = raw_value.strip()
        if separator and key and item_value:
            lines.append(f"{key}:{item_value}")
    return "\n".join(lines)


def _add_template_ref_variables(template: str, variables: list[dict[str, Any]]) -> list[dict[str, Any]]:
    result = [dict(variable) for variable in variables]
    used_names = {str(item.get("variable")) for item in result if item.get("variable")}
    known_selectors = {
        tuple(item.get("value_selector", []))
        for item in result
        if isinstance(item.get("value_selector"), list) and item.get("value_selector")
    }
    for selector in _template_ref_selectors(template):
        selector_key = tuple(selector)
        if selector_key in known_selectors:
            continue
        variable = _unique_template_variable_name(selector, used_names)
        used_names.add(variable)
        known_selectors.add(selector_key)
        result.append({"variable": variable, "value_selector": selector, "value_type": "string"})
    return result


def _template_ref_selectors(template: str) -> list[list[str]]:
    selectors: list[list[str]] = []
    seen: set[tuple[str, str]] = set()
    for match in DIFY_REF_PATTERN.finditer(template):
        selector = (match.group(1), match.group(2))
        if selector in seen:
            continue
        seen.add(selector)
        selectors.append([selector[0], selector[1]])
    return selectors


def _unique_template_variable_name(selector: list[str], used_names: set[str]) -> str:
    preferred = _safe_variable_name(selector[-1] if selector else "value")
    candidates = [preferred, _safe_variable_name("_".join(selector))]
    for candidate in candidates:
        if candidate and candidate not in used_names:
            return candidate
    index = 2
    while f"{preferred}_{index}" in used_names:
        index += 1
    return f"{preferred}_{index}"


def _safe_variable_name(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", value).strip("_")
    if not safe:
        return "value"
    if safe[0].isdigit():
        safe = f"var_{safe}"
    return safe


def _normalize_output(item: dict[str, Any]) -> dict[str, Any]:
    output = dict(item)
    if isinstance(output.get("value_selector"), str):
        output["value_selector"] = _selector_from_ref(output["value_selector"])
    output.setdefault("value_type", "string")
    return output


def _infer_code_outputs(code: str) -> dict[str, dict[str, str | None]]:
    names = []
    for match in re.finditer(r"['\"]([A-Za-z_][A-Za-z0-9_]*)['\"]\s*:", code):
        name = match.group(1)
        if name not in names:
            names.append(name)
    if not names:
        names = ["result"]
    return {name: {"type": _guess_code_output_type(name), "children": None} for name in names}


def _guess_code_output_type(name: str) -> str:
    lowered = name.lower()
    if any(marker in lowered for marker in ("count", "total", "amount", "price", "score", "number")):
        return "number"
    return "string"


def _condition_from_text(text: str) -> dict[str, Any]:
    normalized = normalize_template_refs(text)
    selector_match = re.search(r"\{\{#([A-Za-z0-9_-]+)\.([A-Za-z0-9_.-]+)#\}\}", normalized)
    selector = [selector_match.group(1), selector_match.group(2)] if selector_match else ["start", "query"]
    lowered = normalized.lower()
    if "not contains" in lowered or "不包含" in normalized:
        operator = "not contains"
    elif "contains" in lowered or "包含" in normalized:
        operator = "contains"
    elif "!=" in normalized or "not equal" in lowered:
        operator = "not equal"
    elif "==" in normalized or "=" in normalized or "equal" in lowered:
        operator = "is"
    else:
        operator = "not empty"

    value = ""
    quoted = re.search(r'["\']([^"\']+)["\']', normalized)
    if quoted:
        value = quoted.group(1)
    elif "包含" in normalized:
        value = normalized.rsplit("包含", 1)[-1].strip()

    return {
        "variable_selector": selector,
        "comparison_operator": operator,
        "value": value,
        "varType": "string",
    }


def _selector_from_ref(value: str) -> list[str]:
    normalized = normalize_template_refs(value)
    match = re.search(r"\{\{#([A-Za-z0-9_-]+)\.([A-Za-z0-9_.-]+)#\}\}", normalized)
    if match:
        return [match.group(1), match.group(2)]
    pieces = [piece for piece in value.split(".") if piece]
    return pieces if len(pieces) >= 2 else [value]


def _if_else_edge_positions(edges: list[Any], node_by_id: dict[str, dict[str, Any]]) -> dict[tuple[str, str], int]:
    positions: dict[tuple[str, str], int] = {}
    counters: dict[str, int] = {}
    for edge in edges:
        if not isinstance(edge, dict):
            continue
        source = node_by_id.get(str(edge.get("source")))
        if not source or source.get("type") != "if-else":
            continue
        key = (str(edge.get("source")), str(edge.get("target")))
        positions[key] = counters.get(str(edge.get("source")), 0)
        counters[str(edge.get("source"))] = positions[key] + 1
    return positions


def _infer_if_else_source_handle(
    source: dict[str, Any],
    edge: dict[str, Any],
    node_by_id: dict[str, dict[str, Any]],
    positions: dict[tuple[str, str], int],
) -> str:
    params = source.get("params", {})
    case_ids = [str(case.get("case_id")) for case in params.get("cases", []) if case.get("case_id")]
    valid = {*case_ids, FALSE_HANDLE}
    current = str(edge.get("source_handle", SOURCE_HANDLE))
    if current in valid:
        return current

    target = node_by_id.get(str(edge.get("target")), {})
    target_text = f"{edge.get('target')} {target.get('title') or ''}".lower()
    else_case = str(params.get("else_case", FALSE_HANDLE)).lower()
    for case_id in case_ids:
        if case_id.lower() in target_text:
            return case_id
    if else_case and else_case in target_text:
        return FALSE_HANDLE
    if any(marker in target_text for marker in ("general", "default", "else", "other", "fallback")):
        return FALSE_HANDLE
    branch_ids = [*case_ids, FALSE_HANDLE]
    position = positions.get((str(edge.get("source")), str(edge.get("target"))), 0)
    return branch_ids[position] if position < len(branch_ids) else FALSE_HANDLE


def _input_type(value: str) -> str:
    normalized = value.replace("_", "-")
    mapping = {
        "text": "text-input",
        "string": "paragraph",
        "paragraph": "paragraph",
        "number": "number",
        "integer": "number",
        "boolean": "checkbox",
        "file": "file",
        "image": "file",
        "file-list": "file-list",
        "files": "file-list",
        "json": "json",
    }
    return mapping.get(normalized, "paragraph")


def _default_title(node_type: str) -> str:
    if not node_type:
        return "Node"
    return re.sub(r"(^|-)([a-z])", lambda m: (" " if m.group(1) else "") + m.group(2).upper(), node_type)
