from __future__ import annotations

import re
from copy import deepcopy
from dataclasses import dataclass, field
from typing import Any

from app.input_variables import file_upload_settings, is_file_input_type
from app.list_operator import normalize_list_comparison_operator, normalize_list_variable_selector


SOURCE_HANDLE = "source"
FALSE_HANDLE = "false"
DIFY_REF_PATTERN = re.compile(r"\{\{\s*#([A-Za-z0-9_-]+)\.([A-Za-z0-9_.-]+)#\s*\}\}")
GENERIC_TITLES = {
    "",
    "node",
    "start",
    "begin",
    "input",
    "llm",
    "model",
    "code",
    "end",
    "output",
    "ifelse",
    "if",
    "condition",
    "branch",
    "httprequest",
    "http",
    "template",
    "templatetransform",
    "questionclassifier",
    "classifier",
    "parameterextractor",
    "extractor",
    "variableaggregator",
    "aggregator",
    "variableassigner",
    "assigner",
    "documentextractor",
    "docextractor",
    "listoperator",
    "listfilter",
    "knowledgeretrieval",
    "knowledge",
    "retrieval",
    "rag",
    "humaninput",
    "human",
    "manualinput",
    "approval",
    "开始",
    "开始节点",
    "输入",
    "大模型",
    "模型",
    "代码",
    "结束",
    "结束节点",
    "输出",
    "判断",
    "条件",
    "分支",
    "接口",
    "模板",
    "问题分类",
    "分类器",
    "参数提取",
    "提取器",
    "变量聚合",
    "变量赋值",
    "文档提取",
    "列表处理",
    "列表过滤",
    "知识库检索",
    "知识检索",
    "检索",
    "人工介入",
    "人工输入",
    "人工审核",
    "人工审批",
}

NODE_TYPE_ALIASES = {
    "classifier": "question-classifier",
    "question_classifier": "question-classifier",
    "questionclassifier": "question-classifier",
    "intent-classifier": "question-classifier",
    "intent_classifier": "question-classifier",
    "parameter_extractor": "parameter-extractor",
    "parameterextractor": "parameter-extractor",
    "extractor": "parameter-extractor",
    "param-extractor": "parameter-extractor",
    "param_extractor": "parameter-extractor",
    "variable_aggregator": "variable-aggregator",
    "variableaggregator": "variable-aggregator",
    "aggregator": "variable-aggregator",
    "variable-assigner": "assigner",
    "variable_assigner": "assigner",
    "variableassigner": "assigner",
    "var-assigner": "assigner",
    "var_assigner": "assigner",
    "assigner": "assigner",
    "doc-extractor": "document-extractor",
    "doc_extractor": "document-extractor",
    "docextractor": "document-extractor",
    "document_extractor": "document-extractor",
    "documentextractor": "document-extractor",
    "list-filter": "list-operator",
    "list_filter": "list-operator",
    "listfilter": "list-operator",
    "list_operator": "list-operator",
    "listoperator": "list-operator",
    "knowledge-retrieval": "knowledge-retrieval",
    "knowledge_retrieval": "knowledge-retrieval",
    "knowledgeretrieval": "knowledge-retrieval",
    "knowledge": "knowledge-retrieval",
    "retrieval": "knowledge-retrieval",
    "rag": "knowledge-retrieval",
    "human-input": "human-input",
    "human_input": "human-input",
    "humaninput": "human-input",
    "human": "human-input",
    "manual-input": "human-input",
    "manual_input": "human-input",
    "manualinput": "human-input",
    "approval": "human-input",
    "review": "human-input",
}


@dataclass(frozen=True)
class NormalizationResult:
    payload: dict[str, Any]
    changed: bool
    changes: list[str] = field(default_factory=list)


def normalize_plan_payload(
    payload: dict[str, Any],
    *,
    app_name: str | None = None,
    default_dataset_ids: list[str] | None = None,
) -> NormalizationResult:
    data = deepcopy(payload)
    changes: list[str] = []
    if not isinstance(data, dict):
        raise ValueError("plan payload must be a JSON object")

    if app_name and data.get("name") != app_name:
        data["name"] = app_name
        changes.append("set workflow name from request app_name")
    data.setdefault("name", "Generated Workflow")
    data.setdefault("description", "Generated by chat2dify.")

    nodes = data.get("nodes")
    edges = data.get("edges")
    if not isinstance(nodes, list):
        raise ValueError("plan.nodes must be a list")
    if not isinstance(edges, list):
        raise ValueError("plan.edges must be a list")

    for node in nodes:
        if not isinstance(node, dict):
            raise ValueError("plan.nodes items must be objects")
        old_type = str(node.get("type", ""))
        node_type = _normalize_node_type(old_type)
        if old_type != node_type:
            node["type"] = node_type
            changes.append(f"normalized node type for {node.get('id', '<unknown>')}: {old_type} -> {node_type}")
        node.setdefault("title", _default_title(str(node.get("type", ""))))
        node.setdefault("desc", "")
        params = node.get("params")
        if not isinstance(params, dict):
            params = {}
            node["params"] = params

        node_type = node.get("type")
        before = deepcopy(params)
        match node_type:
            case "start":
                node["params"] = _normalize_start_params(params)
            case "llm":
                node["params"] = _normalize_llm_params(params, workflow_name=str(data.get("name", "")))
            case "code":
                node["params"] = _normalize_code_params(params)
            case "if-else":
                node["params"] = _normalize_if_else_params(params)
            case "end":
                node["params"] = _normalize_end_params(params)
            case "http-request":
                node["params"] = _normalize_http_params(params)
            case "template-transform":
                node["params"] = _normalize_template_params(params)
            case "question-classifier":
                node["params"] = _normalize_question_classifier_params(params)
            case "parameter-extractor":
                node["params"] = _normalize_parameter_extractor_params(params)
            case "variable-aggregator":
                node["params"] = _normalize_variable_aggregator_params(params)
            case "document-extractor":
                node["params"] = _normalize_document_extractor_params(params)
            case "assigner":
                node["params"] = _normalize_assigner_params(params)
            case "list-operator":
                list_params = _normalize_list_operator_params(params)
                if _list_operator_needs_code_fallback(list_params):
                    node["type"] = "code"
                    node["params"] = _normalize_code_params(_object_list_operator_code_params(list_params))
                else:
                    node["params"] = list_params
            case "knowledge-retrieval":
                node["params"] = _normalize_knowledge_retrieval_params(params, default_dataset_ids or [])
            case "human-input":
                node["params"] = _normalize_human_input_params(params)
        if before != node.get("params"):
            changes.append(f"normalized {node.get('id', '<unknown>')} params")

    node_by_id = {str(node.get("id")): node for node in nodes if isinstance(node, dict)}
    for node in nodes:
        if not isinstance(node, dict):
            continue
        old_title = str(node.get("title") or "")
        node_type = str(node.get("type") or "")
        if _is_generic_title(old_title, node_type):
            node["title"] = _semantic_title(node, data, node_by_id, edges)
            changes.append(f"normalized generic title for {node.get('id', '<unknown>')}")

    edge_positions = _branch_edge_positions(edges, node_by_id, "if-else")
    classifier_edge_positions = _branch_edge_positions(edges, node_by_id, "question-classifier")
    human_input_edge_positions = _branch_edge_positions(edges, node_by_id, "human-input")
    for edge in edges:
        if not isinstance(edge, dict):
            raise ValueError("plan.edges items must be objects")
        edge.setdefault("source_handle", SOURCE_HANDLE)
        edge.setdefault("target_handle", "target")
        source = node_by_id.get(str(edge.get("source")))
        if source and source.get("type") == "if-else":
            old_handle = edge.get("source_handle")
            new_handle = _infer_if_else_source_handle(source, edge, node_by_id, edge_positions)
            if old_handle != new_handle:
                edge["source_handle"] = new_handle
                changes.append(f"normalized if-else edge handle for {edge.get('source')} -> {edge.get('target')}")
        elif source and source.get("type") == "question-classifier":
            old_handle = edge.get("source_handle")
            new_handle = _infer_question_classifier_source_handle(
                source,
                edge,
                node_by_id,
                classifier_edge_positions,
            )
            if old_handle != new_handle:
                edge["source_handle"] = new_handle
                changes.append(
                    f"normalized question-classifier edge handle for {edge.get('source')} -> {edge.get('target')}"
                )
        elif source and source.get("type") == "human-input":
            old_handle = edge.get("source_handle")
            new_handle = _infer_human_input_source_handle(source, edge, node_by_id, human_input_edge_positions)
            if old_handle != new_handle:
                edge["source_handle"] = new_handle
                changes.append(f"normalized human-input edge handle for {edge.get('source')} -> {edge.get('target')}")

    return NormalizationResult(payload=data, changed=bool(changes), changes=changes)


def normalize_template_refs(text: str) -> str:
    return re.sub(
        r"\{\{\s*(?!#)([A-Za-z0-9_-]+)\.([A-Za-z0-9_.-]+)\s*\}\}",
        r"{{#\1.\2#}}",
        text,
    )


def _normalize_node_type(value: str) -> str:
    normalized = str(value or "").strip().replace(" ", "-")
    normalized = re.sub(r"-+", "-", normalized)
    alias_key = normalized.lower()
    return NODE_TYPE_ALIASES.get(alias_key, normalized)


def _normalize_start_params(params: dict[str, Any]) -> dict[str, Any]:
    raw_variables = params.get("variables") or params.get("inputs") or []
    variables = []
    for item in raw_variables:
        if not isinstance(item, dict):
            continue
        name = item.get("name") or item.get("variable")
        if not name:
            continue
        input_type = _input_type(str(item.get("type", "paragraph")))
        variable = {
            "name": str(name),
            "type": input_type,
            "required": bool(item.get("required", True)),
            "label": item.get("label") or str(name),
        }
        if item.get("max_length") is not None:
            variable["max_length"] = item.get("max_length")
        if isinstance(item.get("options"), list):
            variable["options"] = deepcopy(item.get("options"))
        if is_file_input_type(input_type):
            variable.update(file_upload_settings(item, input_type=input_type))
        variables.append(variable)
    if not variables:
        variables.append({"name": "query", "type": "paragraph", "required": True, "label": "Query"})
    return {"variables": variables}


def _normalize_llm_params(params: dict[str, Any], *, workflow_name: str) -> dict[str, Any]:
    result = dict(params)
    raw_prompt = str(params.get("prompt", "") or "")
    raw_system = str(params.get("system_prompt", "") or "")
    raw_user = str(params.get("user_prompt", "") or raw_prompt or "")
    split_system, split_user = _split_prompt_sections(raw_user or raw_prompt)

    if not raw_system.strip():
        raw_system = split_system or _default_system_prompt(workflow_name)
        raw_user = split_user or raw_user
    elif split_user and not params.get("user_prompt"):
        raw_user = split_user

    result.pop("prompt", None)
    result["system_prompt"] = normalize_template_refs(_clean_prompt(raw_system))
    result["user_prompt"] = normalize_template_refs(
        _clean_prompt(_ensure_user_prompt(raw_user, workflow_name=workflow_name))
    )
    result.setdefault("completion_params", {"temperature": 0.7})
    return result


def _normalize_code_params(params: dict[str, Any]) -> dict[str, Any]:
    result = dict(params)
    if "language" in result and "code_language" not in result:
        result["code_language"] = result.pop("language")
    result.setdefault("code", "def main(query: str) -> dict:\n    return {\"result\": query}\n")
    result.setdefault("code_language", "python3")
    result["variables"] = _normalize_variables(result.get("variables", []), result.get("inputs"))
    if not result.get("outputs"):
        result["outputs"] = _infer_code_outputs(str(result["code"]))
    return result


def _normalize_if_else_params(params: dict[str, Any]) -> dict[str, Any]:
    raw_cases = params.get("cases") or []
    cases = []
    for idx, raw_case in enumerate(raw_cases):
        if not isinstance(raw_case, dict):
            continue
        case_id = str(raw_case.get("case_id") or raw_case.get("id") or ("true" if idx == 0 else f"case_{idx + 1}"))
        raw_conditions = raw_case.get("conditions")
        if not raw_conditions and raw_case.get("condition"):
            raw_conditions = [_condition_from_text(str(raw_case["condition"]))]
        conditions = []
        for condition in raw_conditions or []:
            if not isinstance(condition, dict):
                continue
            condition_copy = dict(condition)
            if isinstance(condition_copy.get("variable_selector"), str):
                condition_copy["variable_selector"] = _selector_from_ref(condition_copy["variable_selector"])
            condition_copy.setdefault("comparison_operator", "not empty")
            condition_copy.setdefault("value", "")
            condition_copy.setdefault("varType", "string")
            conditions.append(condition_copy)
        cases.append(
            {
                "case_id": case_id,
                "logical_operator": raw_case.get("logical_operator", "and"),
                "conditions": conditions or [
                    {
                        "variable_selector": params.get("variable_selector", ["start", "query"]),
                        "comparison_operator": "not empty",
                        "value": "",
                        "varType": "string",
                    }
                ],
            }
        )
    if not cases:
        cases.append(
            {
                "case_id": "true",
                "logical_operator": "and",
                "conditions": [
                    {
                        "variable_selector": params.get("variable_selector", ["start", "query"]),
                        "comparison_operator": "not empty",
                        "value": "",
                        "varType": "string",
                    }
                ],
            }
        )
    return {"cases": cases, "else_case": str(params.get("else_case", FALSE_HANDLE))}


def _normalize_end_params(params: dict[str, Any]) -> dict[str, Any]:
    outputs = params.get("outputs") or [{"variable": "answer", "value_selector": ["llm", "text"]}]
    return {"outputs": [_normalize_output(item) for item in outputs if isinstance(item, dict)]}


def _normalize_http_params(params: dict[str, Any]) -> dict[str, Any]:
    result = dict(params)
    result["variables"] = _normalize_variables(result.get("variables", []))
    result["method"] = str(result.get("method", "GET")).upper()
    result["url"] = normalize_template_refs(str(result.get("url", "https://example.com")))
    result["headers"] = _normalize_key_value_text(result.get("headers", ""))
    result["params"] = _normalize_key_value_text(result.get("params", ""))
    body = result.get("body", {"type": "none", "data": []})
    if isinstance(body, dict) and isinstance(body.get("data"), str):
        body = {**body, "data": normalize_template_refs(body["data"])}
    elif body in (None, "", [], {}):
        body = {"type": "none", "data": []}
    result["body"] = body
    if result.get("timeout") is None:
        result.pop("timeout", None)
    if result.get("retry_config") is None:
        result.pop("retry_config", None)
    return result


def _normalize_template_params(params: dict[str, Any]) -> dict[str, Any]:
    template = normalize_template_refs(str(params.get("template", "{{ query }}")))
    variables = _normalize_variables(params.get("variables", []))
    return {
        **params,
        "template": template,
        "variables": _add_template_ref_variables(template, variables),
    }


def _normalize_question_classifier_params(params: dict[str, Any]) -> dict[str, Any]:
    result = dict(params)
    raw_selector = (
        result.get("query_variable_selector")
        or result.get("query")
        or result.get("variable_selector")
        or result.get("input_selector")
        or ["start", "query"]
    )
    result["query_variable_selector"] = _normalize_selector(raw_selector)
    result["classes"] = _normalize_classifier_classes(
        result.get("classes") or result.get("topics") or result.get("categories") or result.get("intents") or []
    )
    result["instruction"] = normalize_template_refs(str(result.get("instruction") or result.get("prompt") or ""))
    result.pop("query", None)
    result.pop("variable_selector", None)
    result.pop("input_selector", None)
    result.pop("topics", None)
    result.pop("categories", None)
    result.pop("intents", None)
    result.pop("prompt", None)
    result["vision"] = _normalize_vision(result.get("vision"))
    return result


def _normalize_parameter_extractor_params(params: dict[str, Any]) -> dict[str, Any]:
    result = dict(params)
    raw_selector = (
        result.get("query")
        or result.get("query_variable_selector")
        or result.get("variable_selector")
        or result.get("input_selector")
        or ["start", "query"]
    )
    result["query"] = _normalize_selector(raw_selector)
    result["parameters"] = _normalize_extractor_parameters(
        result.get("parameters") or result.get("fields") or result.get("extract_parameters") or []
    )
    result["instruction"] = normalize_template_refs(str(result.get("instruction") or result.get("prompt") or ""))
    result["reasoning_mode"] = str(result.get("reasoning_mode") or "prompt")
    if result["reasoning_mode"] not in {"prompt", "function_call"}:
        result["reasoning_mode"] = "prompt"
    result.pop("query_variable_selector", None)
    result.pop("variable_selector", None)
    result.pop("input_selector", None)
    result.pop("fields", None)
    result.pop("extract_parameters", None)
    result.pop("prompt", None)
    result["vision"] = _normalize_vision(result.get("vision"))
    return result


def _normalize_variable_aggregator_params(params: dict[str, Any]) -> dict[str, Any]:
    result = dict(params)
    variables = _normalize_selector_list(result.get("variables") or result.get("selectors") or result.get("inputs") or [])
    result["variables"] = variables
    result["output_type"] = _var_type(str(result.get("output_type") or result.get("var_type") or "string"))
    advanced = result.get("advanced_settings") if isinstance(result.get("advanced_settings"), dict) else {}
    groups = []
    for idx, group in enumerate(advanced.get("groups") or result.get("groups") or []):
        if not isinstance(group, dict):
            continue
        group_name = str(group.get("group_name") or group.get("name") or f"Group{idx + 1}")
        group_id = str(group.get("groupId") or group.get("group_id") or _safe_branch_id(group_name) or f"group_{idx + 1}")
        groups.append(
            {
                "group_name": group_name,
                "groupId": group_id,
                "output_type": _var_type(str(group.get("output_type") or result["output_type"])),
                "variables": _normalize_selector_list(group.get("variables") or []),
            }
        )
    group_enabled = bool(advanced.get("group_enabled", False) or groups)
    result["advanced_settings"] = {"group_enabled": group_enabled, "groups": groups if group_enabled else []}
    result.pop("selectors", None)
    result.pop("inputs", None)
    result.pop("groups", None)
    result.pop("var_type", None)
    return result


def _normalize_document_extractor_params(params: dict[str, Any]) -> dict[str, Any]:
    result = dict(params)
    raw_selector = (
        result.get("variable_selector")
        or result.get("file_selector")
        or result.get("input_selector")
        or result.get("variable")
        or result.get("file")
        or ["start", "files"]
    )
    result["variable_selector"] = _normalize_selector(raw_selector)
    result["is_array_file"] = bool(result.get("is_array_file", result.get("array", False)))
    result.pop("file_selector", None)
    result.pop("input_selector", None)
    result.pop("variable", None)
    result.pop("file", None)
    result.pop("array", None)
    return result


def _normalize_assigner_params(params: dict[str, Any]) -> dict[str, Any]:
    result = dict(params)
    items = result.get("items") or result.get("operations") or []
    normalized_items = []
    for item in items:
        if not isinstance(item, dict):
            continue
        variable_selector = _normalize_selector(
            item.get("variable_selector")
            or item.get("assigned_variable_selector")
            or item.get("target")
            or item.get("variable")
            or []
        )
        input_type = str(item.get("input_type") or ("variable" if _looks_like_selector(item.get("value")) else "constant"))
        if input_type not in {"variable", "constant"}:
            input_type = "constant"
        operation = str(item.get("operation") or item.get("write_mode") or item.get("mode") or "over-write")
        value = item.get("value")
        if input_type == "variable":
            value = _normalize_selector(value)
        normalized_items.append(
            {
                "variable_selector": variable_selector,
                "input_type": input_type,
                "operation": operation,
                "value": value,
            }
        )
    result["version"] = str(result.get("version") or "2")
    result["items"] = normalized_items
    result.pop("operations", None)
    return result


def _normalize_list_operator_params(params: dict[str, Any]) -> dict[str, Any]:
    result = dict(params)
    raw_variable = result.get("variable") or result.get("variable_selector") or result.get("input_selector") or ["start", "items"]
    result["variable"] = normalize_list_variable_selector(_normalize_selector(raw_variable))
    result["var_type"] = _array_var_type(str(result.get("var_type") or result.get("type") or "array[string]"))
    result["item_var_type"] = _item_var_type(str(result.get("item_var_type") or result.get("item_type") or ""), result["var_type"])
    result["filter_by"] = _normalize_list_filter(result.get("filter_by") or result.get("filter"))
    result["extract_by"] = _normalize_extract_by(result.get("extract_by") or result.get("extract"))
    result["order_by"] = _normalize_order_by(result.get("order_by") or result.get("sort_by") or result.get("sort"))
    result["limit"] = _normalize_limit(result.get("limit"))
    result.pop("variable_selector", None)
    result.pop("input_selector", None)
    result.pop("type", None)
    result.pop("item_type", None)
    result.pop("filter", None)
    result.pop("extract", None)
    result.pop("sort_by", None)
    result.pop("sort", None)
    return result


def _normalize_knowledge_retrieval_params(params: dict[str, Any], default_dataset_ids: list[str]) -> dict[str, Any]:
    result = dict(params)
    raw_query_selector = (
        result.get("query_variable_selector")
        or result.get("query")
        or result.get("variable_selector")
        or result.get("input_selector")
        or ["start", "query"]
    )
    result["query_variable_selector"] = _normalize_selector(raw_query_selector)
    attachment_selector = result.get("query_attachment_selector") or result.get("attachment_selector") or []
    result["query_attachment_selector"] = _normalize_optional_selector(attachment_selector)
    dataset_ids = _normalize_dataset_ids(result.get("dataset_ids") or result.get("datasets"))
    if not dataset_ids:
        dataset_ids = list(default_dataset_ids)
    result["dataset_ids"] = dataset_ids
    result["retrieval_mode"] = _retrieval_mode(str(result.get("retrieval_mode") or result.get("mode") or "multiple"))
    result["multiple_retrieval_config"] = _normalize_multiple_retrieval_config(
        result.get("multiple_retrieval_config") or result.get("retrieval_config")
    )
    if result["retrieval_mode"] == "single":
        single = result.get("single_retrieval_config") if isinstance(result.get("single_retrieval_config"), dict) else {}
        if single:
            result["single_retrieval_config"] = single
    else:
        result.pop("single_retrieval_config", None)
    result["metadata_filtering_mode"] = str(result.get("metadata_filtering_mode") or "disabled")
    if result["metadata_filtering_mode"] not in {"disabled", "automatic", "manual"}:
        result["metadata_filtering_mode"] = "disabled"
    result["vision"] = _normalize_vision(result.get("vision"))
    result.pop("query", None)
    result.pop("variable_selector", None)
    result.pop("input_selector", None)
    result.pop("attachment_selector", None)
    result.pop("datasets", None)
    result.pop("mode", None)
    result.pop("retrieval_config", None)
    return result


def _normalize_human_input_params(params: dict[str, Any]) -> dict[str, Any]:
    result = dict(params)
    result["delivery_methods"] = _normalize_human_delivery_methods(
        result.get("delivery_methods") or result.get("delivery") or result.get("methods") or []
    )
    result["form_content"] = normalize_template_refs(
        str(
            result.get("form_content")
            or result.get("content")
            or result.get("form")
            or "请审核以下 workflow 中间结果，并选择处理动作。"
        )
    )
    result["inputs"] = _normalize_human_form_inputs(result.get("inputs") or result.get("fields") or result.get("form_inputs") or [])
    result["user_actions"] = _normalize_human_actions(
        result.get("user_actions") or result.get("actions") or result.get("buttons") or []
    )
    result["timeout"] = _positive_int(result.get("timeout"), default=3)
    result["timeout_unit"] = _timeout_unit(str(result.get("timeout_unit") or result.get("timeoutUnit") or "day"))
    result.pop("delivery", None)
    result.pop("methods", None)
    result.pop("content", None)
    result.pop("form", None)
    result.pop("fields", None)
    result.pop("form_inputs", None)
    result.pop("actions", None)
    result.pop("buttons", None)
    result.pop("timeoutUnit", None)
    return result


def _normalize_human_delivery_methods(value: Any) -> list[dict[str, Any]]:
    methods: list[dict[str, Any]] = []
    if isinstance(value, str):
        value = [{"type": value}]
    for idx, item in enumerate(value or []):
        if isinstance(item, str):
            item = {"type": item}
        if not isinstance(item, dict):
            continue
        method_type = str(item.get("type") or "webapp").strip().lower()
        if method_type not in {"webapp", "email", "slack", "teams", "discord"}:
            method_type = "webapp"
        method = {
            "id": str(item.get("id") or f"{method_type}-{idx + 1}"),
            "type": method_type,
            "enabled": bool(item.get("enabled", True)),
        }
        if isinstance(item.get("config"), dict):
            method["config"] = deepcopy(item["config"])
        elif method_type == "webapp":
            method["config"] = {}
        methods.append(method)
    if not methods:
        methods.append({"id": "webapp-1", "type": "webapp", "enabled": True, "config": {}})
    if not any(method.get("enabled") for method in methods):
        methods[0]["enabled"] = True
    return methods


def _normalize_human_form_inputs(value: Any) -> list[dict[str, Any]]:
    inputs: list[dict[str, Any]] = []
    if isinstance(value, dict):
        value = [{"output_variable_name": key, **(item if isinstance(item, dict) else {"type": item})} for key, item in value.items()]
    used_names: set[str] = set()
    for idx, item in enumerate(value or []):
        if isinstance(item, str):
            item = {"output_variable_name": item, "type": "paragraph"}
        if not isinstance(item, dict):
            continue
        raw_name = str(item.get("output_variable_name") or item.get("name") or item.get("variable") or f"input_{idx + 1}")
        output_name = _unique_parameter_name(raw_name, used_names)
        default = item.get("default") if isinstance(item.get("default"), dict) else {}
        default_type = str(default.get("type") or item.get("default_type") or "constant")
        if default_type not in {"constant", "variable"}:
            default_type = "constant"
        default_value = default.get("value", item.get("default_value", ""))
        default_selector = default.get("selector") or item.get("selector") or []
        normalized_default: dict[str, Any] = {"type": default_type}
        if default_type == "variable":
            normalized_default["selector"] = _normalize_optional_selector(default_selector)
            normalized_default["value"] = ""
        else:
            normalized_default["selector"] = _normalize_optional_selector(default_selector)
            normalized_default["value"] = str(default_value or "")
        inputs.append(
            {
                "type": _human_input_type(str(item.get("type") or item.get("input_type") or "paragraph")),
                "output_variable_name": output_name,
                "default": normalized_default,
            }
        )
    return inputs


def _normalize_human_actions(value: Any) -> list[dict[str, Any]]:
    actions: list[dict[str, Any]] = []
    if isinstance(value, dict):
        value = [{"id": key, "title": item} for key, item in value.items()]
    used_ids: set[str] = set()
    for idx, item in enumerate(value or []):
        if isinstance(item, str):
            item = {"id": item, "title": item}
        if not isinstance(item, dict):
            continue
        title = str(item.get("title") or item.get("name") or item.get("label") or "").strip()
        raw_id = str(item.get("id") or item.get("value") or title or f"action_{idx + 1}")
        action_id = _safe_branch_id(raw_id) or f"action_{idx + 1}"
        preferred = action_id
        duplicate_index = 2
        while action_id in used_ids:
            action_id = f"{preferred}_{duplicate_index}"
            duplicate_index += 1
        used_ids.add(action_id)
        if not title:
            title = action_id
        style = str(item.get("button_style") or item.get("style") or ("primary" if idx == 0 else "default"))
        if style not in {"primary", "default", "accent", "ghost"}:
            style = "default"
        actions.append({"id": action_id, "title": title, "button_style": style})
    if not actions:
        actions = [
            {"id": "approve", "title": "通过", "button_style": "primary"},
            {"id": "reject", "title": "驳回", "button_style": "default"},
        ]
    return actions


def _human_input_type(value: str) -> str:
    normalized = str(value or "").strip().lower().replace("_", "-")
    mapping = {
        "text": "text-input",
        "string": "text-input",
        "text-input": "text-input",
        "paragraph": "paragraph",
        "textarea": "paragraph",
        "number": "number",
        "boolean": "checkbox",
        "bool": "checkbox",
        "checkbox": "checkbox",
        "select": "select",
    }
    return mapping.get(normalized, "paragraph")


def _timeout_unit(value: str) -> str:
    normalized = str(value or "").strip().lower()
    if normalized in {"hour", "hours", "h", "小时"}:
        return "hour"
    return "day"


def _positive_int(value: Any, *, default: int) -> int:
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        parsed = default
    return max(1, parsed)


def _normalize_classifier_classes(value: Any) -> list[dict[str, str]]:
    classes: list[dict[str, str]] = []
    if isinstance(value, dict):
        value = [{"id": key, "name": item} for key, item in value.items()]
    for idx, item in enumerate(value or []):
        if isinstance(item, str):
            raw_id = _safe_branch_id(item) or f"class_{idx + 1}"
            name = item
            label = f"CLASS {idx + 1}"
        elif isinstance(item, dict):
            name = str(item.get("name") or item.get("label") or item.get("title") or "").strip()
            raw_id = str(item.get("id") or item.get("case_id") or item.get("value") or name or f"class_{idx + 1}")
            label = str(item.get("label") or f"CLASS {idx + 1}")
        else:
            continue
        if not name:
            name = f"类别{idx + 1}"
        classes.append({"id": _safe_branch_id(raw_id) or f"class_{idx + 1}", "name": name, "label": label})
    return classes


def _normalize_extractor_parameters(value: Any) -> list[dict[str, Any]]:
    parameters: list[dict[str, Any]] = []
    used_names: set[str] = set()
    if isinstance(value, dict):
        value = [{"name": key, **(item if isinstance(item, dict) else {"description": str(item)})} for key, item in value.items()]
    for item in value or []:
        if isinstance(item, str):
            name = _unique_parameter_name(item, used_names)
            parameters.append(
                {
                    "name": name,
                    "type": "string",
                    "description": item,
                    "required": True,
                }
            )
            continue
        if not isinstance(item, dict):
            continue
        name = str(item.get("name") or item.get("variable") or item.get("field") or "").strip()
        if not name:
            continue
        param_type = _parameter_type(str(item.get("type") or item.get("value_type") or "string"))
        safe_name = _unique_parameter_name(name, used_names)
        parameter = {
            "name": safe_name,
            "type": param_type,
            "description": str(item.get("description") or item.get("desc") or name),
            "required": bool(item.get("required", True)),
        }
        options = item.get("options")
        if param_type == "select" and isinstance(options, list):
            parameter["options"] = [str(option) for option in options if str(option)]
        parameters.append(parameter)
    return parameters


def _unique_parameter_name(value: str, used_names: set[str]) -> str:
    preferred = _parameter_name(value)
    candidate = preferred
    index = 2
    while candidate in used_names:
        candidate = f"{preferred}_{index}"
        index += 1
    used_names.add(candidate)
    return candidate


def _parameter_name(value: str) -> str:
    raw = str(value or "").strip()
    mapping = {
        "车型": "car_model",
        "车牌": "license_plate",
        "门店": "store",
        "订单": "order_id",
        "订单号": "order_id",
        "手机号": "phone",
        "电话": "phone",
        "时间": "time",
        "预约时间": "appointment_time",
        "诉求": "request",
        "问题": "issue",
        "姓名": "name",
        "客户姓名": "customer_name",
    }
    return mapping.get(raw, _safe_variable_name(raw))


def _normalize_selector(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item) for item in value if str(item)]
    if isinstance(value, str):
        return _selector_from_ref(value)
    return ["start", "query"]


def _normalize_optional_selector(value: Any) -> list[str]:
    if value in (None, "", [], {}):
        return []
    selector = _normalize_selector(value)
    return selector if len(selector) >= 2 else []


def _normalize_selector_list(value: Any) -> list[list[str]]:
    selectors: list[list[str]] = []
    if isinstance(value, dict):
        value = list(value.values())
    for item in value or []:
        if isinstance(item, dict):
            raw_selector = item.get("value_selector") or item.get("variable_selector") or item.get("selector") or item.get("value")
        else:
            raw_selector = item
        selector = _normalize_selector(raw_selector)
        if len(selector) >= 2:
            selectors.append(selector)
    return selectors


def _normalize_dataset_ids(value: Any) -> list[str]:
    if isinstance(value, str):
        raw_items = value.split(",")
    elif isinstance(value, list):
        raw_items = value
    else:
        raw_items = []
    dataset_ids = []
    for item in raw_items:
        if isinstance(item, dict):
            item = item.get("id") or item.get("dataset_id")
        text = str(item or "").strip()
        if text:
            dataset_ids.append(text)
    return dataset_ids


def _retrieval_mode(value: str) -> str:
    normalized = str(value or "").strip().lower().replace("_", "-")
    if normalized in {"single", "one-way", "oneway"}:
        return "single"
    return "multiple"


def _normalize_multiple_retrieval_config(value: Any) -> dict[str, Any]:
    config = value if isinstance(value, dict) else {}
    try:
        top_k = int(config.get("top_k", 4))
    except (TypeError, ValueError):
        top_k = 4
    score_threshold = config.get("score_threshold")
    if score_threshold in ("", "none", "None"):
        score_threshold = None
    result = {
        "top_k": max(1, top_k),
        "score_threshold": score_threshold,
        "reranking_enable": bool(config.get("reranking_enable", False)),
        "reranking_mode": str(config.get("reranking_mode") or "reranking_model"),
    }
    reranking_model = _normalize_reranking_model(config.get("reranking_model"))
    if result["reranking_enable"] and reranking_model:
        result["reranking_model"] = reranking_model
    if isinstance(config.get("weights"), dict):
        result["weights"] = deepcopy(config["weights"])
    return result


def _normalize_reranking_model(value: Any) -> dict[str, str] | None:
    if not isinstance(value, dict):
        return None
    provider = str(value.get("provider") or value.get("reranking_provider_name") or "").strip()
    model = str(value.get("model") or value.get("reranking_model_name") or "").strip()
    if not provider or not model:
        return None
    return {"provider": provider, "model": model}


def _looks_like_selector(value: Any) -> bool:
    if isinstance(value, list):
        return len(value) >= 2 and all(isinstance(item, str | int | float | bool) for item in value)
    if isinstance(value, str):
        return bool(DIFY_REF_PATTERN.search(normalize_template_refs(value)) or len([piece for piece in value.split(".") if piece]) >= 2)
    return False


def _normalize_vision(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        enabled = bool(value.get("enabled", False))
        configs = value.get("configs") if isinstance(value.get("configs"), dict) else {"variable_selector": []}
        configs.setdefault("variable_selector", [])
        return {"enabled": enabled, "configs": configs}
    return {"enabled": False, "configs": {"variable_selector": []}}


def _var_type(value: str) -> str:
    normalized = str(value or "").strip().lower().replace("_", "-")
    mapping = {
        "str": "string",
        "text": "string",
        "paragraph": "string",
        "integer": "number",
        "int": "number",
        "float": "number",
        "bool": "boolean",
        "boolean": "boolean",
        "object": "object",
        "dict": "object",
        "array-string": "array[string]",
        "string[]": "array[string]",
        "array-number": "array[number]",
        "number[]": "array[number]",
        "array-object": "array[object]",
        "object[]": "array[object]",
        "array-boolean": "array[boolean]",
        "array-bool": "array[boolean]",
        "boolean[]": "array[boolean]",
        "array-file": "array[file]",
        "file[]": "array[file]",
        "file-list": "array[file]",
        "arrayfile": "array[file]",
    }
    allowed = {
        "string",
        "number",
        "boolean",
        "object",
        "array[string]",
        "array[number]",
        "array[object]",
        "array[boolean]",
        "array[file]",
        "file",
        "any",
    }
    return mapping.get(normalized, normalized if normalized in allowed else "string")


def _array_var_type(value: str) -> str:
    var_type = _var_type(value)
    if var_type.startswith("array["):
        return var_type
    return f"array[{var_type if var_type != 'any' else 'string'}]"


def _item_var_type(value: str, array_type: str) -> str:
    explicit = _var_type(value)
    if value and not explicit.startswith("array["):
        return explicit
    if array_type.startswith("array[") and array_type.endswith("]"):
        return array_type.removeprefix("array[").removesuffix("]")
    return "string"


def _normalize_list_filter(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict):
        return {"enabled": False, "conditions": []}
    conditions = []
    for item in value.get("conditions") or []:
        if not isinstance(item, dict):
            continue
        condition = dict(item)
        condition["key"] = str(condition.get("key", ""))
        condition["comparison_operator"] = normalize_list_comparison_operator(
            condition.get("comparison_operator") or condition.get("operator") or "contains"
        )
        condition.setdefault("value", "")
        conditions.append(condition)
    return {"enabled": bool(value.get("enabled", False)), "conditions": conditions}


def _normalize_extract_by(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict):
        return {"enabled": False, "serial": "1"}
    return {"enabled": bool(value.get("enabled", False)), "serial": str(value.get("serial") or value.get("index") or "1")}


def _normalize_order_by(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict):
        return {"enabled": False, "key": "", "value": "asc"}
    order = str(value.get("value") or value.get("order") or "asc").lower()
    if order not in {"asc", "desc"}:
        order = "asc"
    key = value.get("key", "")
    if isinstance(key, str):
        normalized_key: str | list[str] = key
    elif isinstance(key, list):
        normalized_key = _normalize_selector(key)
    else:
        normalized_key = ""
    return {"enabled": bool(value.get("enabled", False)), "key": normalized_key, "value": order}


def _normalize_limit(value: Any) -> dict[str, Any]:
    if isinstance(value, int):
        return {"enabled": True, "size": max(1, value)}
    if not isinstance(value, dict):
        return {"enabled": False, "size": 10}
    size = value.get("size", 10)
    try:
        size_int = int(size)
    except (TypeError, ValueError):
        size_int = 10
    return {"enabled": bool(value.get("enabled", False)), "size": max(1, size_int)}


def _list_operator_needs_code_fallback(params: dict[str, Any]) -> bool:
    return params.get("var_type") == "array[object]" or params.get("item_var_type") == "object"


def _object_list_operator_code_params(params: dict[str, Any]) -> dict[str, Any]:
    filter_by = params.get("filter_by") if isinstance(params.get("filter_by"), dict) else {}
    order_by = params.get("order_by") if isinstance(params.get("order_by"), dict) else {}
    limit = params.get("limit") if isinstance(params.get("limit"), dict) else {}
    code = f"""def main(records: list) -> dict:
    conditions = {repr(filter_by.get("conditions") if filter_by.get("enabled") else [])}
    order_enabled = {repr(bool(order_by.get("enabled")))}
    order_key = {repr(order_by.get("key", ""))}
    order_desc = {repr(str(order_by.get("value") or "asc").lower() == "desc")}
    limit_enabled = {repr(bool(limit.get("enabled")))}
    limit_size = {repr(max(1, int(limit.get("size", 10))))}

    def get_value(item, key):
        current = item
        for part in str(key or "").split("."):
            if not part:
                continue
            if not isinstance(current, dict):
                return None
            current = current.get(part)
        return current

    def as_number(value):
        try:
            return float(value)
        except (TypeError, ValueError):
            return None

    def compare(actual, operator, expected):
        if operator in ("empty", "is null", "null"):
            return actual in (None, "", [], {{}})
        if operator in ("not empty", "is not null", "not null"):
            return actual not in (None, "", [], {{}})
        if operator == "contains":
            return str(expected) in str(actual or "")
        if operator == "not contains":
            return str(expected) not in str(actual or "")
        if operator == "start with":
            return str(actual or "").startswith(str(expected))
        if operator == "end with":
            return str(actual or "").endswith(str(expected))
        if operator in ("=", "is"):
            return actual == expected or str(actual) == str(expected)
        if operator in ("≠", "is not"):
            return not (actual == expected or str(actual) == str(expected))
        if operator in (">", "<", "≥", "≤"):
            left = as_number(actual)
            right = as_number(expected)
            if left is None or right is None:
                return False
            if operator == ">":
                return left > right
            if operator == "<":
                return left < right
            if operator == "≥":
                return left >= right
            return left <= right
        if operator in ("in", "not in"):
            values = expected if isinstance(expected, list) else [part.strip() for part in str(expected).split(",")]
            matched = actual in values or str(actual) in [str(value) for value in values]
            return matched if operator == "in" else not matched
        return True

    def matches(item):
        if not conditions:
            return True
        for condition in conditions:
            key = condition.get("key", "")
            actual = get_value(item, key) if key else item
            operator = condition.get("comparison_operator") or "contains"
            expected = condition.get("value", "")
            if not compare(actual, operator, expected):
                return False
        return True

    source = records if isinstance(records, list) else []
    result = [item for item in source if isinstance(item, dict) and matches(item)]
    if order_enabled and order_key:
        result.sort(key=lambda item: get_value(item, order_key) or "", reverse=order_desc)
    if limit_enabled:
        result = result[:limit_size]
    return {{
        "result": result,
        "first_record": result[0] if result else {{}},
        "last_record": result[-1] if result else {{}},
    }}
"""
    return {
        "code_language": "python3",
        "code": code,
        "variables": [{"variable": "records", "value_selector": params.get("variable"), "value_type": "array[object]"}],
        "outputs": {
            "result": {"type": "array[object]", "children": None},
            "first_record": {"type": "object", "children": None},
            "last_record": {"type": "object", "children": None},
        },
    }


def _parameter_type(value: str) -> str:
    normalized = value.strip().lower().replace("_", "-")
    mapping = {
        "str": "string",
        "text": "string",
        "paragraph": "string",
        "integer": "number",
        "int": "number",
        "float": "number",
        "bool": "boolean",
        "boolean": "boolean",
        "enum": "select",
        "choice": "select",
        "array-string": "array[string]",
        "array_string": "array[string]",
        "string[]": "array[string]",
        "array-number": "array[number]",
        "array_number": "array[number]",
        "number[]": "array[number]",
        "array-object": "array[object]",
        "array_object": "array[object]",
        "object[]": "array[object]",
        "array-boolean": "array[boolean]",
        "array_bool": "array[boolean]",
        "boolean[]": "array[boolean]",
    }
    return mapping.get(normalized, normalized if normalized in _allowed_parameter_types() else "string")


def _allowed_parameter_types() -> set[str]:
    return {
        "string",
        "number",
        "boolean",
        "select",
        "array[string]",
        "array[number]",
        "array[object]",
        "array[boolean]",
    }


def _safe_branch_id(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_-]", "_", str(value or "").strip())
    safe = re.sub(r"_+", "_", safe).strip("_")
    return safe


def _split_prompt_sections(text: str) -> tuple[str, str]:
    normalized = normalize_template_refs(str(text or "").strip())
    if not normalized:
        return "", ""

    explicit = _split_explicit_prompt_sections(normalized)
    if explicit:
        return explicit

    system_lines: list[str] = []
    user_lines: list[str] = []
    for raw_line in normalized.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if DIFY_REF_PATTERN.search(line) and _looks_like_system_instruction(line):
            mixed_system, mixed_user = _split_mixed_prompt_line(line)
            system_lines.extend(mixed_system)
            user_lines.extend(mixed_user)
        elif DIFY_REF_PATTERN.search(line):
            user_lines.append(line)
        elif _looks_like_system_instruction(line):
            system_lines.append(line)
        else:
            user_lines.append(line)

    if system_lines and user_lines:
        return "\n".join(system_lines), "\n".join(user_lines)
    return "", normalized


def _split_explicit_prompt_sections(text: str) -> tuple[str, str] | None:
    labels = [
        ("system", r"(?:system_prompt|system|系统提示词|系统)\s*[:：]"),
        ("user", r"(?:user_prompt|user|用户提示词|用户)\s*[:：]"),
    ]
    matches: list[tuple[int, int, str]] = []
    for section, pattern in labels:
        for match in re.finditer(pattern, text, flags=re.IGNORECASE):
            matches.append((match.start(), match.end(), section))
    matches.sort(key=lambda item: item[0])
    if len({section for _, _, section in matches}) < 2:
        return None

    sections: dict[str, list[str]] = {"system": [], "user": []}
    for idx, (_, content_start, section) in enumerate(matches):
        content_end = matches[idx + 1][0] if idx + 1 < len(matches) else len(text)
        content = text[content_start:content_end].strip()
        if content:
            sections[section].append(content)
    system_text = "\n".join(sections["system"]).strip()
    user_text = "\n".join(sections["user"]).strip()
    if system_text or user_text:
        return system_text, user_text
    return None


def _split_mixed_prompt_line(line: str) -> tuple[list[str], list[str]]:
    system_parts: list[str] = []
    user_parts: list[str] = []
    parts = [part.strip() for part in re.split(r"(?<=[。；;!！?？])\s*", line) if part.strip()]
    if not parts:
        return [], [line]

    for part in parts:
        if DIFY_REF_PATTERN.search(part):
            user_parts.append(part)
        elif _looks_like_system_instruction(part):
            system_parts.append(part)
        else:
            user_parts.append(part)
    if not system_parts or not user_parts:
        return [], [line]
    return system_parts, user_parts


def _looks_like_system_instruction(line: str) -> bool:
    lowered = line.lower()
    markers = (
        "你是",
        "角色",
        "身份",
        "规则",
        "输出格式",
        "审核",
        "标准",
        "不得",
        "禁止",
        "必须",
        "只输出",
        "不要",
        "保持",
        "tone",
        "role",
        "rules",
        "format",
        "criteria",
        "must",
        "never",
        "do not",
    )
    return any(marker in lowered or marker in line for marker in markers)


def _clean_prompt(text: str) -> str:
    return re.sub(r"\n{3,}", "\n\n", str(text or "").strip())


def _ensure_user_prompt(text: str, *, workflow_name: str) -> str:
    prompt = _clean_prompt(text)
    if DIFY_REF_PATTERN.search(normalize_template_refs(prompt)):
        return prompt
    subject = _workflow_subject(workflow_name)
    if prompt:
        return f"{prompt}\n\n请处理以下用户输入：{{{{#start.query#}}}}"
    return f"请根据以下用户输入完成{subject}任务：{{{{#start.query#}}}}"


def _default_system_prompt(workflow_name: str) -> str:
    subject = _workflow_subject(workflow_name)
    return (
        f"你是{subject}专员，负责根据用户输入生成专业、礼貌、可执行的回复。\n"
        "规则：先理解用户诉求，再给出清晰处理建议；不得编造订单、金额、门店或政策信息；"
        "遇到不确定信息时说明需要进一步核实。\n"
        "输出格式：用自然中文输出，结构清楚，语气友好。\n"
        "审核标准：回复必须贴合用户输入，不推卸责任，不承诺超出权限的赔付或处理结果。"
    )


def _semantic_title(
    node: dict[str, Any],
    data: dict[str, Any],
    node_by_id: dict[str, dict[str, Any]],
    edges: list[Any],
) -> str:
    node_type = str(node.get("type") or "")
    params = node.get("params", {}) if isinstance(node.get("params"), dict) else {}
    subject = _workflow_subject(str(data.get("name") or data.get("description") or "业务"))
    subject = subject[:16]

    match node_type:
        case "start":
            return f"接收{subject}诉求"
        case "llm":
            prompt_text = f"{params.get('system_prompt', '')}\n{params.get('user_prompt', '')}\n{node.get('id', '')}"
            branch = _branch_label_from_text(prompt_text)
            if branch:
                return f"生成{branch}回复"
            return f"生成{subject}回复"
        case "if-else":
            return f"判断{subject}类型"
        case "code":
            return f"处理{subject}数据"
        case "http-request":
            return f"调用{subject}接口"
        case "template-transform":
            return f"整理{subject}内容"
        case "question-classifier":
            return f"识别{subject}类型"
        case "parameter-extractor":
            return f"提取{subject}信息"
        case "variable-aggregator":
            return f"聚合{subject}变量"
        case "document-extractor":
            return f"提取{subject}文档文本"
        case "assigner":
            return f"更新{subject}变量"
        case "list-operator":
            return f"筛选{subject}列表"
        case "knowledge-retrieval":
            return f"检索{subject}知识库"
        case "human-input":
            return f"人工审核{subject}"
        case "end":
            upstream = _first_upstream(node, node_by_id, edges)
            if upstream and upstream.get("type") == "llm":
                upstream_title = str(upstream.get("title") or "")
                if not _is_generic_title(upstream_title, "llm") and upstream_title.startswith("生成"):
                    return upstream_title.replace("生成", "返回", 1).replace("回复", "结果")
            return f"返回{subject}结果"
    return f"{subject}节点"


def _first_upstream(
    node: dict[str, Any],
    node_by_id: dict[str, dict[str, Any]],
    edges: list[Any],
) -> dict[str, Any] | None:
    node_id = str(node.get("id") or "")
    for edge in edges:
        if isinstance(edge, dict) and str(edge.get("target") or "") == node_id:
            return node_by_id.get(str(edge.get("source") or ""))
    return None


def _branch_label_from_text(text: str) -> str:
    lowered = text.lower()
    mapping = [
        ("退款", "退款处理"),
        ("refund", "退款处理"),
        ("发票", "发票处理"),
        ("invoice", "发票处理"),
        ("投诉", "投诉安抚"),
        ("complaint", "投诉安抚"),
        ("售后", "售后服务"),
        ("after-sales", "售后服务"),
        ("urgent", "紧急问题"),
        ("紧急", "紧急问题"),
    ]
    for marker, label in mapping:
        if marker in lowered or marker in text:
            return label
    return ""


def _workflow_subject(value: str) -> str:
    text = re.sub(r"\s+", " ", str(value or "")).strip()
    text = re.sub(r"(?i)\b(workflow|flow|assistant|bot)\b", "", text)
    for suffix in ("工作流", "流程", "机器人", "助手", "自动化", "处理"):
        text = text.replace(suffix, "")
    text = text.strip(" -_：:，,。.")
    return text or "业务"


def _is_generic_title(title: str, node_type: str) -> bool:
    normalized = re.sub(r"[\s_\-]+", "", str(title or "").strip().lower())
    default = re.sub(r"[\s_\-]+", "", _default_title(node_type).lower())
    return normalized in GENERIC_TITLES or normalized == default


def _normalize_variables(items: Any, inputs: Any = None) -> list[dict[str, Any]]:
    variables = []
    for item in items or []:
        if not isinstance(item, dict):
            continue
        variable = item.get("variable")
        selector = item.get("value_selector")
        if variable and selector:
            variables.append(_normalize_output({"variable": str(variable), "value_selector": selector}))
    if isinstance(inputs, dict):
        for variable, ref in inputs.items():
            variables.append(_normalize_output({"variable": str(variable), "value_selector": _selector_from_ref(str(ref))}))
    return variables


def _normalize_key_value_text(value: Any) -> str:
    if value in (None, "", [], {}):
        return ""
    if isinstance(value, dict):
        lines = [
            f"{str(key).strip()}:{normalize_template_refs(str(item)).strip()}"
            for key, item in value.items()
            if str(key).strip() and str(item).strip()
        ]
        return "\n".join(lines)
    if isinstance(value, list):
        lines = []
        for item in value:
            if not isinstance(item, dict):
                continue
            key = str(item.get("key", "")).strip()
            raw_value = item.get("value", "")
            item_value = normalize_template_refs(str(raw_value)).strip()
            if key and item_value:
                lines.append(f"{key}:{item_value}")
        return "\n".join(lines)

    text = str(value).strip()
    if text in {"[]", "{}", "null", "None"}:
        return ""
    lines = []
    for line in normalize_template_refs(text).splitlines():
        key, separator, raw_value = line.partition(":")
        key = key.strip()
        item_value = raw_value.strip()
        if separator and key and item_value:
            lines.append(f"{key}:{item_value}")
    return "\n".join(lines)


def _add_template_ref_variables(template: str, variables: list[dict[str, Any]]) -> list[dict[str, Any]]:
    result = [dict(variable) for variable in variables]
    used_names = {str(item.get("variable")) for item in result if item.get("variable")}
    known_selectors = {
        tuple(item.get("value_selector", []))
        for item in result
        if isinstance(item.get("value_selector"), list) and item.get("value_selector")
    }
    for selector in _template_ref_selectors(template):
        selector_key = tuple(selector)
        if selector_key in known_selectors:
            continue
        variable = _unique_template_variable_name(selector, used_names)
        used_names.add(variable)
        known_selectors.add(selector_key)
        result.append({"variable": variable, "value_selector": selector, "value_type": "string"})
    return result


def _template_ref_selectors(template: str) -> list[list[str]]:
    selectors: list[list[str]] = []
    seen: set[tuple[str, str]] = set()
    for match in DIFY_REF_PATTERN.finditer(template):
        selector = (match.group(1), match.group(2))
        if selector in seen:
            continue
        seen.add(selector)
        selectors.append([selector[0], selector[1]])
    return selectors


def _unique_template_variable_name(selector: list[str], used_names: set[str]) -> str:
    preferred = _safe_variable_name(selector[-1] if selector else "value")
    candidates = [preferred, _safe_variable_name("_".join(selector))]
    for candidate in candidates:
        if candidate and candidate not in used_names:
            return candidate
    index = 2
    while f"{preferred}_{index}" in used_names:
        index += 1
    return f"{preferred}_{index}"


def _safe_variable_name(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", value).strip("_")
    if not safe:
        return "value"
    if safe[0].isdigit():
        safe = f"var_{safe}"
    return safe


def _normalize_output(item: dict[str, Any]) -> dict[str, Any]:
    output = dict(item)
    if isinstance(output.get("value_selector"), str):
        output["value_selector"] = _selector_from_ref(output["value_selector"])
    output.setdefault("value_type", "string")
    return output


def _infer_code_outputs(code: str) -> dict[str, dict[str, str | None]]:
    names = []
    for match in re.finditer(r"['\"]([A-Za-z_][A-Za-z0-9_]*)['\"]\s*:", code):
        name = match.group(1)
        if name not in names:
            names.append(name)
    if not names:
        names = ["result"]
    return {name: {"type": _guess_code_output_type(name), "children": None} for name in names}


def _guess_code_output_type(name: str) -> str:
    lowered = name.lower()
    if any(marker in lowered for marker in ("count", "total", "amount", "price", "score", "number")):
        return "number"
    return "string"


def _condition_from_text(text: str) -> dict[str, Any]:
    normalized = normalize_template_refs(text)
    selector_match = re.search(r"\{\{#([A-Za-z0-9_-]+)\.([A-Za-z0-9_.-]+)#\}\}", normalized)
    selector = [selector_match.group(1), selector_match.group(2)] if selector_match else ["start", "query"]
    lowered = normalized.lower()
    if "not contains" in lowered or "不包含" in normalized:
        operator = "not contains"
    elif "contains" in lowered or "包含" in normalized:
        operator = "contains"
    elif "!=" in normalized or "not equal" in lowered:
        operator = "not equal"
    elif "==" in normalized or "=" in normalized or "equal" in lowered:
        operator = "is"
    else:
        operator = "not empty"

    value = ""
    quoted = re.search(r'["\']([^"\']+)["\']', normalized)
    if quoted:
        value = quoted.group(1)
    elif "包含" in normalized:
        value = normalized.rsplit("包含", 1)[-1].strip()

    return {
        "variable_selector": selector,
        "comparison_operator": operator,
        "value": value,
        "varType": "string",
    }


def _selector_from_ref(value: str) -> list[str]:
    normalized = normalize_template_refs(value)
    match = re.search(r"\{\{#([A-Za-z0-9_-]+)\.([A-Za-z0-9_.-]+)#\}\}", normalized)
    if match:
        return [match.group(1), *[piece for piece in match.group(2).split(".") if piece]]
    pieces = [piece for piece in value.split(".") if piece]
    return pieces if len(pieces) >= 2 else [value]


def _branch_edge_positions(
    edges: list[Any],
    node_by_id: dict[str, dict[str, Any]],
    node_type: str,
) -> dict[tuple[str, str], int]:
    positions: dict[tuple[str, str], int] = {}
    counters: dict[str, int] = {}
    for edge in edges:
        if not isinstance(edge, dict):
            continue
        source = node_by_id.get(str(edge.get("source")))
        if not source or source.get("type") != node_type:
            continue
        key = (str(edge.get("source")), str(edge.get("target")))
        positions[key] = counters.get(str(edge.get("source")), 0)
        counters[str(edge.get("source"))] = positions[key] + 1
    return positions


def _infer_if_else_source_handle(
    source: dict[str, Any],
    edge: dict[str, Any],
    node_by_id: dict[str, dict[str, Any]],
    positions: dict[tuple[str, str], int],
) -> str:
    params = source.get("params", {})
    case_ids = [str(case.get("case_id")) for case in params.get("cases", []) if case.get("case_id")]
    valid = {*case_ids, FALSE_HANDLE}
    current = str(edge.get("source_handle", SOURCE_HANDLE))
    if current in valid:
        return current

    target = node_by_id.get(str(edge.get("target")), {})
    target_text = f"{edge.get('target')} {target.get('title') or ''}".lower()
    else_case = str(params.get("else_case", FALSE_HANDLE)).lower()
    for case_id in case_ids:
        if case_id.lower() in target_text:
            return case_id
    if else_case and else_case in target_text:
        return FALSE_HANDLE
    if any(marker in target_text for marker in ("general", "default", "else", "other", "fallback")):
        return FALSE_HANDLE
    branch_ids = [*case_ids, FALSE_HANDLE]
    position = positions.get((str(edge.get("source")), str(edge.get("target"))), 0)
    return branch_ids[position] if position < len(branch_ids) else FALSE_HANDLE


def _infer_question_classifier_source_handle(
    source: dict[str, Any],
    edge: dict[str, Any],
    node_by_id: dict[str, dict[str, Any]],
    positions: dict[tuple[str, str], int],
) -> str:
    classes = source.get("params", {}).get("classes", [])
    class_ids = [str(item.get("id")) for item in classes if isinstance(item, dict) and item.get("id")]
    valid = set(class_ids)
    current = str(edge.get("source_handle", SOURCE_HANDLE))
    if current in valid:
        return current

    target = node_by_id.get(str(edge.get("target")), {})
    target_text = f"{edge.get('target')} {target.get('title') or ''}".lower()
    for item in classes:
        if not isinstance(item, dict):
            continue
        class_id = str(item.get("id") or "")
        class_name = str(item.get("name") or "")
        if class_id and (class_id.lower() in target_text or class_name.lower() in target_text or class_name in target_text):
            return class_id
    position = positions.get((str(edge.get("source")), str(edge.get("target"))), 0)
    return class_ids[position] if position < len(class_ids) else current


def _infer_human_input_source_handle(
    source: dict[str, Any],
    edge: dict[str, Any],
    node_by_id: dict[str, dict[str, Any]],
    positions: dict[tuple[str, str], int],
) -> str:
    actions = source.get("params", {}).get("user_actions", [])
    action_ids = [str(item.get("id")) for item in actions if isinstance(item, dict) and item.get("id")]
    valid = set(action_ids)
    current = str(edge.get("source_handle", SOURCE_HANDLE))
    if current in valid:
        return current

    target = node_by_id.get(str(edge.get("target")), {})
    target_text = f"{edge.get('target')} {target.get('title') or ''}".lower()
    for item in actions:
        if not isinstance(item, dict):
            continue
        action_id = str(item.get("id") or "")
        title = str(item.get("title") or "")
        if action_id and (action_id.lower() in target_text or title.lower() in target_text or title in target_text):
            return action_id
    position = positions.get((str(edge.get("source")), str(edge.get("target"))), 0)
    return action_ids[position] if position < len(action_ids) else current


def _input_type(value: str) -> str:
    normalized = value.replace("_", "-")
    mapping = {
        "text": "text-input",
        "string": "paragraph",
        "paragraph": "paragraph",
        "number": "number",
        "integer": "number",
        "boolean": "checkbox",
        "file": "file",
        "image": "file",
        "file-list": "file-list",
        "files": "file-list",
        "json": "json",
        "json-object": "json",
    }
    return mapping.get(normalized, "paragraph")


def _default_title(node_type: str) -> str:
    if not node_type:
        return "Node"
    return re.sub(r"(^|-)([a-z])", lambda m: (" " if m.group(1) else "") + m.group(2).upper(), node_type)
