from fastapi.testclient import TestClient
import pytest

from app.assistant import AssistantPlanRequest, plan_assistant_action
from app.config import Settings
from app.dify.client import DifyAppDetail
from app.dify.version import DifyVersionInfo
from app.main import app


def test_assistant_create_router_detects_all_app_modes() -> None:
    cases = [
        ("创建一个工作流处理售后投诉", "workflow"),
        ("create a Chatflow for support", "advanced-chat"),
        ("创建一个聊天助手回答售后问题", "chat"),
        ("create an Agent for after-sales triage", "agent-chat"),
        ("创建一个文本生成应用总结维修单", "completion"),
    ]
    for message, app_mode in cases:
        result = plan_assistant_action(AssistantPlanRequest(message=message))
        assert result.status == "pending_action"
        assert result.action is not None
        assert result.action.operation == "workflow.create"
        assert result.action.payload["app_mode"] == app_mode


def test_assistant_create_requires_explicit_app_mode_even_with_old_context() -> None:
    result = plan_assistant_action(
        AssistantPlanRequest(
            message="创建一个处理售后投诉的应用",
            context={"app_mode": "workflow", "app_id": "old-app"},
        )
    )

    assert result.status == "needs_input"
    assert result.missing_fields == ["app_mode"]


def test_assistant_create_uses_follow_up_app_mode_in_pending_draft() -> None:
    result = plan_assistant_action(
        AssistantPlanRequest(message="创建一个处理售后投诉的应用\n用 Chatflow")
    )

    assert result.status == "pending_action"
    assert result.action is not None
    assert result.action.operation == "workflow.create"
    assert result.action.payload["app_mode"] == "advanced-chat"


def test_assistant_create_infers_app_name_and_description_from_request() -> None:
    result = plan_assistant_action(
        AssistantPlanRequest(message="创建一个工作流，帮我处理503房间天花板漏水投诉")
    )

    assert result.status == "pending_action"
    assert result.action is not None
    assert result.action.payload["app_name"] != "Generated Workflow"
    assert "503房间天花板漏水" in result.action.payload["app_name"]
    assert result.action.payload["app_description"] != "Generated by chat2dify."
    assert "503房间天花板漏水" in result.action.payload["app_description"]


def test_assistant_create_asks_when_name_and_purpose_are_too_vague() -> None:
    result = plan_assistant_action(AssistantPlanRequest(message="创建一个工作流"))

    assert result.status == "needs_input"
    assert "app_name" in result.missing_fields
    assert "app_description" in result.missing_fields


def test_assistant_modify_preview_and_apply_router() -> None:
    preview = plan_assistant_action(
        AssistantPlanRequest(
            message="修改 app_id app-123 把回复改得更温暖",
            context={"app_mode": "chat"},
        )
    )
    assert preview.status == "pending_action"
    assert preview.action is not None
    assert preview.action.operation == "workflow.modify.draft"
    assert preview.action.payload["app_id"] == "app-123"

    apply = plan_assistant_action(
        AssistantPlanRequest(
            message="确认修改并应用",
            context={
                "app_mode": "advanced-chat",
                "modify_preview": {
                    "app_id": "app-123",
                    "message": "把回复改得更温暖",
                    "base_hash": "hash-1",
                    "plan": {
                        "name": "Support",
                        "app_mode": "advanced-chat",
                        "nodes": [],
                        "edges": [],
                    },
                },
            },
        )
    )
    assert apply.status == "pending_action"
    assert apply.action is not None
    assert apply.action.operation == "workflow.modify.apply"
    assert apply.action.payload["expected_hash"] == "hash-1"
    assert apply.action.payload["plan"]["app_mode"] == "advanced-chat"


def test_assistant_modify_apply_uses_configured_preview_config() -> None:
    result = plan_assistant_action(
        AssistantPlanRequest(
            message="应用修改",
            context={
                "modify_preview": {
                    "app_id": "chat-app-1",
                    "app_mode": "chat",
                    "message": "把回复改得更温暖",
                    "base_hash": "hash-1",
                    "configured_model_config": {"pre_prompt": "warm", "updated_at": "hash-1"},
                    "configured_model_config_changes": [
                        {"type": "prompt_changed", "target": "pre_prompt"}
                    ],
                },
            },
        )
    )

    assert result.status == "pending_action"
    assert result.action is not None
    assert result.action.operation == "workflow.modify.apply"
    assert result.action.payload["expected_hash"] == "hash-1"
    assert result.action.payload["configured_model_config"]["pre_prompt"] == "warm"


def test_assistant_modify_uses_active_app_context_without_retyping_app_id() -> None:
    result = plan_assistant_action(
        AssistantPlanRequest(
            message="把回复改得更温暖",
            context={
                "active_app": {
                    "app_id": "chat-app-1",
                    "app_mode": "chat",
                    "expected_hash": "hash-1",
                }
            },
        )
    )

    assert result.status == "pending_action"
    assert result.action is not None
    assert result.action.payload["app_id"] == "chat-app-1"
    assert "expected_hash" not in result.action.payload


def test_assistant_modify_preview_does_not_send_stale_context_hash() -> None:
    result = plan_assistant_action(
        AssistantPlanRequest(
            message="修改这个工作流，把回复改得更温暖",
            context={
                "active_app": {
                    "app_id": "workflow-app-1",
                    "app_mode": "workflow",
                    "expected_hash": "stale-hash",
                }
            },
        )
    )

    assert result.status == "pending_action"
    assert result.action is not None
    assert result.action.payload["app_id"] == "workflow-app-1"
    assert "expected_hash" not in result.action.payload


def test_assistant_modify_preview_keeps_explicit_hash() -> None:
    result = plan_assistant_action(
        AssistantPlanRequest(
            message="修改 app_id workflow-app-1 hash current-hash 把回复改得更温暖",
            context={"app_mode": "workflow"},
        )
    )

    assert result.status == "pending_action"
    assert result.action is not None
    assert result.action.payload["expected_hash"] == "current-hash"


def test_assistant_run_router_detects_all_run_operations() -> None:
    cases = [
        ("workflow", "workflow.run.draft", {"run_inputs": {"query": "hi"}}),
        ("advanced-chat", "chatflow.run.draft", {"run_query": "hi"}),
        ("chat", "chatbot.run.draft", {"run_query": "hi"}),
        ("completion", "completion.run.draft", {"run_query": "source text"}),
        ("agent-chat", "agent.run.draft", {"run_query": "analyze this"}),
    ]
    for app_mode, operation, extra_context in cases:
        result = plan_assistant_action(
            AssistantPlanRequest(
                message="运行",
                context={"app_mode": app_mode, "app_id": "app-123", **extra_context},
            )
        )
        assert result.status == "pending_action"
        assert result.action is not None
        assert result.action.operation == operation
        assert result.action.payload["app_id"] == "app-123"


def test_assistant_run_uses_active_app_context_and_natural_query() -> None:
    result = plan_assistant_action(
        AssistantPlanRequest(
            message="测试运行：我要投诉订单配送太慢",
            context={"active_app": {"app_id": "chat-app-1", "app_mode": "chat"}},
        )
    )

    assert result.status == "pending_action"
    assert result.action is not None
    assert result.action.operation == "chatbot.run.draft"
    assert result.action.payload["app_id"] == "chat-app-1"
    assert result.action.payload["query"] == "我要投诉订单配送太慢"


def test_assistant_run_uses_recent_app_for_explicit_mode() -> None:
    result = plan_assistant_action(
        AssistantPlanRequest(
            message="运行刚才的 Chatflow：我要投诉订单配送太慢",
            context={
                "active_app": {"app_id": "agent-app-1", "app_mode": "agent-chat"},
                "recent_apps": {
                    "advanced-chat": {"app_id": "chatflow-app-1", "app_mode": "advanced-chat"}
                },
            },
        )
    )

    assert result.status == "pending_action"
    assert result.action is not None
    assert result.action.operation == "chatflow.run.draft"
    assert result.action.payload["app_id"] == "chatflow-app-1"
    assert result.action.payload["query"] == "我要投诉订单配送太慢"


def test_assistant_extracts_app_id_from_url_and_prefixed_token() -> None:
    from_url = plan_assistant_action(
        AssistantPlanRequest(
            message="修改 http://dify.local/app/chat-app-123/configuration 把回复改得更温暖",
            context={"app_mode": "chat"},
        )
    )
    from_token = plan_assistant_action(
        AssistantPlanRequest(
            message="修改 chat-app-456 把回复改得更温暖",
            context={"app_mode": "chat"},
        )
    )

    assert from_url.status == "pending_action"
    assert from_url.action is not None
    assert from_url.action.payload["app_id"] == "chat-app-123"
    assert from_token.status == "pending_action"
    assert from_token.action is not None
    assert from_token.action.payload["app_id"] == "chat-app-456"


def test_assistant_workflow_run_accepts_natural_query_and_prefers_json_inputs() -> None:
    natural = plan_assistant_action(
        AssistantPlanRequest(
            message="测试运行：我要投诉订单配送太慢",
            context={"active_app": {"app_id": "workflow-app-1", "app_mode": "workflow"}},
        )
    )
    explicit_json = plan_assistant_action(
        AssistantPlanRequest(
            message='测试运行 {"query":"JSON 输入","priority":"high"} 我要投诉订单配送太慢',
            context={"active_app": {"app_id": "workflow-app-1", "app_mode": "workflow"}},
        )
    )

    assert natural.status == "pending_action"
    assert natural.action is not None
    assert natural.action.operation == "workflow.run.draft"
    assert natural.action.payload["inputs"] == {"query": "我要投诉订单配送太慢"}
    assert explicit_json.status == "pending_action"
    assert explicit_json.action is not None
    assert explicit_json.action.payload["inputs"] == {"query": "JSON 输入", "priority": "high"}


def test_assistant_workflow_run_asks_then_accepts_follow_up_natural_input() -> None:
    missing = plan_assistant_action(
        AssistantPlanRequest(
            message="测试运行下这个工作流",
            context={"active_app": {"app_id": "workflow-app-1", "app_mode": "workflow"}},
        )
    )
    follow_up = plan_assistant_action(
        AssistantPlanRequest(
            message="测试运行下这个工作流\n测试输入：“为什么503房间天花板一直在漏水”",
            context={"active_app": {"app_id": "workflow-app-1", "app_mode": "workflow"}},
        )
    )

    assert missing.status == "needs_input"
    assert missing.missing_fields == ["inputs"]
    assert follow_up.status == "pending_action"
    assert follow_up.action is not None
    assert follow_up.action.payload["inputs"] == {"query": "为什么503房间天花板一直在漏水"}


def test_assistant_run_router_requires_workflow_inputs() -> None:
    result = plan_assistant_action(
        AssistantPlanRequest(
            message="运行 workflow app_id app-123",
            context={"app_mode": "workflow"},
        )
    )
    assert result.status == "needs_input"
    assert result.missing_fields == ["inputs"]


def test_assistant_plan_api_does_not_submit_task(monkeypatch, tmp_path) -> None:
    settings = _test_settings(tmp_path)
    monkeypatch.setattr("app.main.load_settings", lambda: settings)
    monkeypatch.setattr(
        "app.main.read_dify_version_info",
        lambda _: DifyVersionInfo("../dify", "test", "9.9.9"),
    )

    def fail_submit(*_args, **_kwargs):
        raise AssertionError("plan must not submit background tasks")

    monkeypatch.setattr("app.main._submit_task", fail_submit)

    with TestClient(app) as client:
        response = client.post(
            "/api/assistant/plan",
            json={"message": "创建一个 Chatflow 帮我处理售后投诉"},
        )

    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "pending_action"
    assert data["action"]["operation"] == "workflow.create"


def test_assistant_web_ui_assets_are_present(monkeypatch, tmp_path) -> None:
    settings = _test_settings(tmp_path)
    monkeypatch.setattr("app.main.load_settings", lambda: settings)
    monkeypatch.setattr(
        "app.main.read_dify_version_info",
        lambda _: DifyVersionInfo("../dify", "test", "9.9.9"),
    )

    with TestClient(app) as client:
        index = client.get("/")
        script = client.get("/static/app.js")

    assert index.status_code == 200
    assert 'id="chat-form"' in index.text
    assert 'id="chat-log"' in index.text
    assert 'id="chat-input"' in index.text
    assert 'id="create-form"' not in index.text
    assert "/api/assistant/plan" in script.text
    assert "/api/assistant/execute" in script.text
    assert "pendingAction" in script.text
    assert "executePendingAction" in script.text
    assert "addActionCard" in script.text
    assert "active_app" in script.text
    assert "recent_apps" in script.text
    assert "configured_model_config" in script.text
    assert "prepareApplyActionFromPreview" in script.text
    assert "workflow.modify.apply" in script.text
    assert "尚未写回 Dify" in script.text
    assert "applyContextHints(text)" not in script.text


@pytest.mark.parametrize(
    ("operation", "payload"),
    [
        ("workflow.create", {"message": "创建 workflow", "app_mode": "workflow"}),
        ("workflow.create", {"message": "创建 chatflow", "app_mode": "advanced-chat"}),
        ("workflow.create", {"message": "创建聊天助手", "app_mode": "chat"}),
        ("workflow.create", {"message": "创建 agent", "app_mode": "agent-chat"}),
        ("workflow.create", {"message": "创建文本生成", "app_mode": "completion"}),
        ("workflow.modify.draft", {"app_id": "app-1", "message": "改暖一点"}),
        (
            "workflow.modify.apply",
            {
                "app_id": "app-1",
                "message": "改暖一点",
                "expected_hash": "hash-1",
            },
        ),
        ("workflow.run.draft", {"app_id": "app-1", "inputs": {"query": "hi"}}),
        ("chatflow.run.draft", {"app_id": "app-1", "query": "hi"}),
        ("chatbot.run.draft", {"app_id": "app-1", "query": "hi"}),
        ("completion.run.draft", {"app_id": "app-1", "query": "hi"}),
        ("agent.run.draft", {"app_id": "app-1", "query": "hi"}),
    ],
)
def test_assistant_execute_api_submits_supported_tasks(monkeypatch, tmp_path, operation, payload) -> None:
    settings = _test_settings(tmp_path)
    monkeypatch.setattr("app.main.load_settings", lambda: settings)
    monkeypatch.setattr(
        "app.main.read_dify_version_info",
        lambda _: DifyVersionInfo("../dify", "test", "9.9.9"),
    )
    seen = {}

    def fake_submit(_request, submitted_operation, submitted_payload, _runner):
        seen["operation"] = submitted_operation
        seen["payload"] = submitted_payload
        return {
            "task_id": "task-1",
            "operation": submitted_operation,
            "status": "queued",
            "request": submitted_payload,
        }

    monkeypatch.setattr("app.main._submit_task", fake_submit)

    with TestClient(app) as client:
        response = client.post(
            "/api/assistant/execute",
            json={
                "action": {
                    "operation": operation,
                    "panel": "create" if operation == "workflow.create" else "run",
                    "kind": "create" if operation == "workflow.create" else "run",
                    "summary": "confirm",
                    "payload": payload,
                }
            },
        )

    assert response.status_code == 202
    assert seen["operation"] == operation
    assert response.json()["task_id"] == "task-1"


def test_assistant_execute_configured_preview_apply_writes_reviewed_model_config(monkeypatch, tmp_path) -> None:
    settings = _test_settings(tmp_path)
    current_config = {
        "model": {"provider": "openai", "name": "gpt-4o", "mode": "chat"},
        "pre_prompt": "旧提示词",
        "updated_at": "hash-1",
    }
    preview_config = {
        "model": {"provider": "openai", "name": "gpt-4o", "mode": "chat"},
        "pre_prompt": "预览确认后的提示词",
        "updated_at": "hash-1",
    }
    seen = {}

    class FakeDifyClient:
        def __init__(self, _settings):
            pass

        def __enter__(self):
            return self

        def __exit__(self, *_args):
            pass

        def get_app_detail(self, app_id):
            raw_config = seen.get("payload") or current_config
            return DifyAppDetail(
                id=app_id,
                name="售后聊天助手",
                mode="chat",
                description="",
                raw={"model_config": raw_config},
            )

        def get_draft_workflow(self, _app_id):
            raise AssertionError("Configured app apply must not load workflow draft.")

        def update_model_config(self, app_id, payload):
            seen["app_id"] = app_id
            seen["payload"] = payload
            return {"result": "success", "updated_at": "hash-2"}

    class FakeTaskContext:
        def update(self, *_args, **_kwargs):
            pass

        def raise_if_cancelled(self):
            pass

    def fake_submit(_request, submitted_operation, submitted_payload, runner):
        result = runner(FakeTaskContext())
        return {
            "task_id": "task-1",
            "operation": submitted_operation,
            "status": "succeeded",
            "request": submitted_payload,
            "result": result,
        }

    monkeypatch.setattr("app.main.load_settings", lambda: settings)
    monkeypatch.setattr(
        "app.main.read_dify_version_info",
        lambda _: DifyVersionInfo("../dify", "test", "9.9.9"),
    )
    monkeypatch.setattr("app.main.DifyClient", FakeDifyClient)
    monkeypatch.setattr("app.main._runtime_model_context", lambda *_args, **_kwargs: (None, []))
    monkeypatch.setattr("app.main._submit_task", fake_submit)

    with TestClient(app) as client:
        response = client.post(
            "/api/assistant/execute",
            json={
                "action": {
                    "operation": "workflow.modify.apply",
                    "app_mode": "chat",
                    "panel": "modify",
                    "kind": "modify-apply",
                    "summary": "apply reviewed config",
                    "payload": {
                        "app_id": "chat-app-1",
                        "message": "这句话如果被重新解释会追加到提示词里",
                        "expected_hash": "hash-1",
                        "configured_model_config": preview_config,
                        "configured_model_config_changes": [
                            {"type": "prompt_changed", "target": "pre_prompt"}
                        ],
                    },
                }
            },
        )

    assert response.status_code == 202
    data = response.json()
    assert seen["app_id"] == "chat-app-1"
    assert seen["payload"] == preview_config
    assert data["result"]["planner"]["mode"] == "chat-config-preview"
    assert data["result"]["new_hash"] == "hash-2"


def test_assistant_execute_api_rejects_invalid_payload(monkeypatch, tmp_path) -> None:
    settings = _test_settings(tmp_path)
    monkeypatch.setattr("app.main.load_settings", lambda: settings)
    monkeypatch.setattr(
        "app.main.read_dify_version_info",
        lambda _: DifyVersionInfo("../dify", "test", "9.9.9"),
    )

    with TestClient(app) as client:
        response = client.post(
            "/api/assistant/execute",
            json={
                "action": {
                    "operation": "workflow.run.draft",
                    "panel": "run",
                    "kind": "run",
                    "summary": "confirm",
                    "payload": {"app_id": "app-1"},
                }
            },
        )

    assert response.status_code == 422
    assert response.json()["detail"]["code"] == "ASSISTANT_ACTION_INVALID"


def _test_settings(tmp_path) -> Settings:
    return Settings.from_env(
        {
            "DIFY_SOURCE_DIR": "../dify",
            "OPENAI_API_KEY": "token",
            "PLANNER_DEFAULT_PROVIDER": "openai",
            "DIFY_CONSOLE_WEB_BASE": "http://dify.local",
            "DIFY_DEFAULT_MODEL_PROVIDER": "langgenius/tongyi/tongyi",
            "DIFY_DEFAULT_MODEL_NAME": "qwen3.5-plus",
            "CHAT2DIFY_TASK_DB": str(tmp_path / "tasks.sqlite3"),
        },
        validate_dify=False,
    )
