from __future__ import annotations

from typing import Any

import yaml

from app.config import Settings
from app.dify.client import DifyModelListItem


def compile_agent_app_dsl(
    *,
    message: str,
    app_name: str | None,
    dsl_version: str,
    settings: Settings,
    model_selections: list[DifyModelListItem] | None = None,
    tool_selections: list[dict[str, Any]] | None = None,
) -> str:
    model = (model_selections or [None])[0]
    model_provider = getattr(model, "provider", None) or settings.dify_default_model_provider
    model_name = getattr(model, "model", None) or settings.dify_default_model_name
    name = app_name or _title_from_message(message)
    model_config = {
        "model": {
            "provider": model_provider,
            "name": model_name,
            "mode": "chat",
            "completion_params": {"temperature": 0.7},
        },
        "pre_prompt": _agent_pre_prompt(message),
        "prompt_type": "simple",
        "chat_prompt_config": {},
        "completion_prompt_config": {},
        "user_input_form": [],
        "dataset_query_variable": "",
        "dataset_configs": {"retrieval_model": "multiple", "datasets": {"datasets": []}},
        "agent_mode": {
            "enabled": True,
            "strategy": "react",
            "tools": _agent_tools(tool_selections or []),
            "prompt": _agent_prompt(message),
        },
        "opening_statement": "",
        "suggested_questions": [],
        "suggested_questions_after_answer": {"enabled": False},
        "speech_to_text": {"enabled": False},
        "text_to_speech": {"enabled": False},
        "more_like_this": {"enabled": False},
        "sensitive_word_avoidance": {"enabled": False, "type": "", "config": {}},
        "retriever_resource": {"enabled": False},
        "external_data_tools": [],
        "file_upload": {
            "image": {
                "enabled": False,
                "number_limits": 3,
                "detail": "high",
                "transfer_methods": ["local_file", "remote_url"],
            }
        },
    }
    data = {
        "version": dsl_version,
        "kind": "app",
        "app": {
            "name": name,
            "mode": "agent-chat",
            "icon": "🤖",
            "icon_type": "emoji",
            "icon_background": "#FFEAD5",
            "description": "Generated by chat2dify.",
            "use_icon_as_answer_icon": False,
        },
        "model_config": model_config,
        "dependencies": [],
    }
    return yaml.safe_dump(data, allow_unicode=True, sort_keys=False)


def agent_app_plan_payload(
    *,
    message: str,
    app_name: str | None,
    settings: Settings,
    model_selections: list[DifyModelListItem] | None = None,
    tool_selections: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    model = (model_selections or [None])[0]
    return {
        "name": app_name or _title_from_message(message),
        "description": "Generated by chat2dify.",
        "app_mode": "agent-chat",
        "agent_mode": {
            "enabled": True,
            "strategy": "react",
            "tools": _agent_tools(tool_selections or []),
            "prompt": _agent_prompt(message),
        },
        "model": {
            "provider": getattr(model, "provider", None) or settings.dify_default_model_provider,
            "name": getattr(model, "model", None) or settings.dify_default_model_name,
            "mode": "chat",
        },
    }


def validate_agent_app_dsl(dsl: str, *, expected_dsl_version: str) -> list[dict[str, Any]]:
    issues: list[dict[str, Any]] = []
    try:
        data = yaml.safe_load(dsl)
    except yaml.YAMLError as exc:
        return [{"code": "DSL_YAML_INVALID", "message": str(exc), "severity": "error"}]
    if not isinstance(data, dict):
        return [{"code": "DSL_INVALID", "message": "DSL root must be a mapping.", "severity": "error"}]
    if str(data.get("version")) != expected_dsl_version:
        issues.append(
            {
                "code": "DSL_VERSION_MISMATCH",
                "message": f"Expected DSL version {expected_dsl_version}, got {data.get('version')}.",
                "severity": "error",
            }
        )
    app = data.get("app") if isinstance(data.get("app"), dict) else {}
    if app.get("mode") != "agent-chat":
        issues.append(
            {
                "code": "DSL_APP_MODE_INVALID",
                "message": "Agent app DSL must use app.mode agent-chat.",
                "path": "app.mode",
                "severity": "error",
            }
        )
    model_config = data.get("model_config") if isinstance(data.get("model_config"), dict) else {}
    agent_mode = model_config.get("agent_mode") if isinstance(model_config.get("agent_mode"), dict) else {}
    if not agent_mode.get("enabled"):
        issues.append(
            {
                "code": "AGENT_MODE_DISABLED",
                "message": "Agent app DSL must enable model_config.agent_mode.",
                "path": "model_config.agent_mode.enabled",
                "severity": "error",
            }
        )
    model = model_config.get("model") if isinstance(model_config.get("model"), dict) else {}
    if not model.get("provider") or not model.get("name"):
        issues.append(
            {
                "code": "AGENT_MODEL_INVALID",
                "message": "Agent app DSL requires model provider and name.",
                "path": "model_config.model",
                "severity": "error",
            }
        )
    return issues


def _agent_pre_prompt(message: str) -> str:
    return (
        "You are an autonomous assistant. Understand the user's request, plan the "
        "steps needed, use configured tools when helpful, and return a concise, "
        f"actionable answer.\n\nTask:\n{message}"
    )


def _agent_prompt(message: str) -> str:
    return (
        "Reason step by step internally. When a tool is available and relevant, "
        "use it before finalizing. Do not invent facts, IDs, prices, policies, or "
        f"tool results.\n\nPrimary task:\n{message}"
    )


def _agent_tools(tool_selections: list[dict[str, Any]]) -> list[dict[str, Any]]:
    tools: list[dict[str, Any]] = []
    for item in tool_selections:
        if not isinstance(item, dict):
            continue
        provider_type = str(item.get("provider_type") or "").strip()
        provider_id = str(item.get("provider_id") or "").strip()
        tool_name = str(item.get("tool_name") or "").strip()
        if not provider_type or not provider_id or not tool_name:
            continue
        tool: dict[str, Any] = {
            "enabled": True,
            "provider_type": provider_type,
            "provider_id": provider_id,
            "tool_name": tool_name,
            "tool_parameters": item.get("tool_parameters")
            if isinstance(item.get("tool_parameters"), dict)
            else {},
        }
        plugin_unique_identifier = item.get("plugin_unique_identifier")
        if plugin_unique_identifier:
            tool["plugin_unique_identifier"] = plugin_unique_identifier
        tools.append(tool)
    return tools


def _title_from_message(message: str) -> str:
    title = " ".join(message.strip().split())
    if not title:
        return "Generated Agent"
    return title[:40]
