from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator


NodeType = Literal[
    "start",
    "llm",
    "code",
    "if-else",
    "end",
    "http-request",
    "template-transform",
    "question-classifier",
    "parameter-extractor",
    "variable-aggregator",
    "document-extractor",
    "assigner",
    "list-operator",
    "knowledge-retrieval",
    "human-input",
    "iteration",
    "iteration-start",
    "loop",
    "loop-start",
    "loop-end",
    "tool",
    "agent",
    "datasource",
    "datasource-empty",
    "knowledge-index",
    "trigger-webhook",
    "trigger-plugin",
    "trigger-schedule",
]
ENTRY_NODE_TYPES = {"start", "datasource", "trigger-webhook", "trigger-plugin", "trigger-schedule"}
InputType = Literal["text", "paragraph", "number", "boolean", "file", "file-list", "json"]


class PlanVariable(BaseModel):
    name: str = Field(min_length=1)
    type: InputType = "paragraph"
    required: bool = True
    label: str | None = None


class PlanEdge(BaseModel):
    source: str = Field(min_length=1)
    target: str = Field(min_length=1)
    source_handle: str = "source"
    target_handle: str = "target"


class PlanNode(BaseModel):
    id: str = Field(min_length=1)
    type: NodeType
    title: str | None = None
    desc: str = ""
    params: dict[str, Any] = Field(default_factory=dict)


class WorkflowPlan(BaseModel):
    name: str = "Generated Workflow"
    description: str = "Generated by chat2dify."
    nodes: list[PlanNode]
    edges: list[PlanEdge]

    @model_validator(mode="after")
    def validate_graph(self) -> "WorkflowPlan":
        node_ids = [node.id for node in self.nodes]
        if len(node_ids) != len(set(node_ids)):
            raise ValueError("node ids must be unique")

        node_id_set = set(node_ids)
        for edge in self.edges:
            if edge.source not in node_id_set:
                raise ValueError(f"edge references unknown source node: {edge.source}")
            if edge.target not in node_id_set:
                raise ValueError(f"edge references unknown target node: {edge.target}")

        starts = [node for node in self.nodes if node.type in ENTRY_NODE_TYPES]
        ends = [node for node in self.nodes if node.type == "end"]
        if len(starts) != 1:
            raise ValueError("workflow must contain exactly one entry node")
        if not ends:
            raise ValueError("workflow must contain at least one end node")

        connected = {edge.source for edge in self.edges} | {edge.target for edge in self.edges}
        isolated = [node.id for node in self.nodes if node.id not in connected and len(self.nodes) > 1]
        if isolated:
            raise ValueError(f"workflow contains isolated nodes: {', '.join(isolated)}")

        reachable = _reachable_from(starts[0].id, self.edges)
        unreachable = [node.id for node in self.nodes if node.id not in reachable]
        if unreachable:
            raise ValueError(f"nodes are not reachable from entry node: {', '.join(unreachable)}")
        return self


def _reachable_from(start_id: str, edges: list[PlanEdge]) -> set[str]:
    graph: dict[str, list[str]] = {}
    for edge in edges:
        graph.setdefault(edge.source, []).append(edge.target)

    seen = {start_id}
    stack = [start_id]
    while stack:
        node_id = stack.pop()
        for target in graph.get(node_id, []):
            if target not in seen:
                seen.add(target)
                stack.append(target)
    return seen


class WorkflowToolSelection(BaseModel):
    provider_id: str = Field(min_length=1)
    provider_type: str = Field(min_length=1)
    tool_name: str = Field(min_length=1)
    provider_name: str | None = None
    tool_label: str | None = None
    description: str | None = None
    parameters: list[dict[str, Any]] = Field(default_factory=list)
    output_schema: dict[str, Any] | None = None
    plugin_id: str | None = None
    plugin_unique_identifier: str | None = None
    tool_parameters: dict[str, Any] = Field(default_factory=dict)
    tool_configurations: dict[str, Any] = Field(default_factory=dict)
    is_team_authorization: bool | None = None
    requires_configuration: bool | None = None


class WorkflowAgentSelection(BaseModel):
    agent_strategy_provider_name: str = Field(min_length=1)
    agent_strategy_name: str = Field(min_length=1)
    agent_strategy_label: str | None = None
    description: str | None = None
    parameters: list[dict[str, Any]] = Field(default_factory=list)
    features: list[str] = Field(default_factory=list)
    output_schema: dict[str, Any] | None = None
    plugin_id: str | None = None
    plugin_unique_identifier: str | None = None
    meta: dict[str, Any] | None = None
    agent_parameters: dict[str, Any] = Field(default_factory=dict)
    requires_configuration: bool | None = None


class WorkflowPlannerSelection(BaseModel):
    provider: Literal["openai", "nvidia"]
    model: str = Field(min_length=1)


class WorkflowRequest(BaseModel):
    message: str = Field(min_length=1)
    app_name: str | None = None
    dry_run: bool = False
    dataset_ids: list[str] | None = None
    tool_selections: list[WorkflowToolSelection] | None = None
    agent_selections: list[WorkflowAgentSelection] | None = None
    planner: WorkflowPlannerSelection | None = None


class WorkflowModifyRequest(BaseModel):
    app_id: str = Field(min_length=1)
    message: str = Field(min_length=1)
    expected_hash: str | None = None
    allow_destructive: bool = False
    plan: WorkflowPlan | None = None
    dataset_ids: list[str] | None = None
    tool_selections: list[WorkflowToolSelection] | None = None
    agent_selections: list[WorkflowAgentSelection] | None = None
    planner: WorkflowPlannerSelection | None = None


class WorkflowRunDraftRequest(BaseModel):
    app_id: str = Field(min_length=1)
    inputs: dict[str, Any]
    files: list[dict[str, Any]] | None = None
    timeout_seconds: float = Field(default=120, gt=0)


class ValidationIssue(BaseModel):
    code: str
    message: str
    node_id: str | None = None
    severity: Literal["error", "warning"] = "error"
    path: str | None = None
    suggestion: str | None = None
