from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator


NodeType = Literal[
    "start",
    "llm",
    "code",
    "if-else",
    "end",
    "http-request",
    "template-transform",
    "question-classifier",
    "parameter-extractor",
    "variable-aggregator",
    "document-extractor",
    "assigner",
    "list-operator",
    "knowledge-retrieval",
    "human-input",
]
InputType = Literal["text", "paragraph", "number", "boolean", "file", "file-list", "json"]


class PlanVariable(BaseModel):
    name: str = Field(min_length=1)
    type: InputType = "paragraph"
    required: bool = True
    label: str | None = None


class PlanEdge(BaseModel):
    source: str = Field(min_length=1)
    target: str = Field(min_length=1)
    source_handle: str = "source"
    target_handle: str = "target"


class PlanNode(BaseModel):
    id: str = Field(min_length=1)
    type: NodeType
    title: str | None = None
    desc: str = ""
    params: dict[str, Any] = Field(default_factory=dict)


class WorkflowPlan(BaseModel):
    name: str = "Generated Workflow"
    description: str = "Generated by chat2dify."
    nodes: list[PlanNode]
    edges: list[PlanEdge]

    @model_validator(mode="after")
    def validate_graph(self) -> "WorkflowPlan":
        node_ids = [node.id for node in self.nodes]
        if len(node_ids) != len(set(node_ids)):
            raise ValueError("node ids must be unique")

        node_id_set = set(node_ids)
        for edge in self.edges:
            if edge.source not in node_id_set:
                raise ValueError(f"edge references unknown source node: {edge.source}")
            if edge.target not in node_id_set:
                raise ValueError(f"edge references unknown target node: {edge.target}")

        starts = [node for node in self.nodes if node.type == "start"]
        ends = [node for node in self.nodes if node.type == "end"]
        if len(starts) != 1:
            raise ValueError("workflow must contain exactly one start node")
        if not ends:
            raise ValueError("workflow must contain at least one end node")

        connected = {edge.source for edge in self.edges} | {edge.target for edge in self.edges}
        isolated = [node.id for node in self.nodes if node.id not in connected and len(self.nodes) > 1]
        if isolated:
            raise ValueError(f"workflow contains isolated nodes: {', '.join(isolated)}")

        reachable = _reachable_from(starts[0].id, self.edges)
        unreachable = [node.id for node in self.nodes if node.id not in reachable]
        if unreachable:
            raise ValueError(f"nodes are not reachable from start: {', '.join(unreachable)}")
        return self


def _reachable_from(start_id: str, edges: list[PlanEdge]) -> set[str]:
    graph: dict[str, list[str]] = {}
    for edge in edges:
        graph.setdefault(edge.source, []).append(edge.target)

    seen = {start_id}
    stack = [start_id]
    while stack:
        node_id = stack.pop()
        for target in graph.get(node_id, []):
            if target not in seen:
                seen.add(target)
                stack.append(target)
    return seen


class WorkflowRequest(BaseModel):
    message: str = Field(min_length=1)
    app_name: str | None = None
    dry_run: bool = False
    dataset_ids: list[str] | None = None


class WorkflowModifyRequest(BaseModel):
    app_id: str = Field(min_length=1)
    message: str = Field(min_length=1)
    expected_hash: str | None = None
    allow_destructive: bool = False
    plan: WorkflowPlan | None = None
    dataset_ids: list[str] | None = None


class WorkflowRunDraftRequest(BaseModel):
    app_id: str = Field(min_length=1)
    inputs: dict[str, Any]
    files: list[dict[str, Any]] | None = None
    timeout_seconds: float = Field(default=120, gt=0)


class ValidationIssue(BaseModel):
    code: str
    message: str
    node_id: str | None = None
    severity: Literal["error", "warning"] = "error"
    path: str | None = None
    suggestion: str | None = None
