from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator


NodeType = Literal[
    "start",
    "llm",
    "code",
    "if-else",
    "end",
    "answer",
    "http-request",
    "template-transform",
    "question-classifier",
    "parameter-extractor",
    "variable-aggregator",
    "document-extractor",
    "assigner",
    "list-operator",
    "knowledge-retrieval",
    "human-input",
    "iteration",
    "iteration-start",
    "loop",
    "loop-start",
    "loop-end",
    "tool",
    "agent",
    "datasource",
    "datasource-empty",
    "knowledge-index",
    "trigger-webhook",
    "trigger-plugin",
    "trigger-schedule",
]
AppMode = Literal["workflow", "advanced-chat"]
ENTRY_NODE_TYPES = {"start", "datasource", "trigger-webhook", "trigger-plugin", "trigger-schedule"}
InputType = Literal["text", "paragraph", "number", "boolean", "file", "file-list", "json"]


class PlanVariable(BaseModel):
    name: str = Field(min_length=1)
    type: InputType = "paragraph"
    required: bool = True
    label: str | None = None


class PlanEdge(BaseModel):
    source: str = Field(min_length=1)
    target: str = Field(min_length=1)
    source_handle: str = "source"
    target_handle: str = "target"


class PlanNode(BaseModel):
    id: str = Field(min_length=1)
    type: NodeType
    title: str | None = None
    desc: str = ""
    params: dict[str, Any] = Field(default_factory=dict)


class WorkflowPlan(BaseModel):
    name: str = "Generated Workflow"
    description: str = "Generated by chat2dify."
    app_mode: AppMode = "workflow"
    nodes: list[PlanNode]
    edges: list[PlanEdge]

    @model_validator(mode="after")
    def validate_graph(self) -> "WorkflowPlan":
        node_ids = [node.id for node in self.nodes]
        if len(node_ids) != len(set(node_ids)):
            raise ValueError("node ids must be unique")

        node_id_set = set(node_ids)
        for edge in self.edges:
            if edge.source not in node_id_set:
                raise ValueError(f"edge references unknown source node: {edge.source}")
            if edge.target not in node_id_set:
                raise ValueError(f"edge references unknown target node: {edge.target}")

        starts = [node for node in self.nodes if node.type == "start"]
        triggers = [
            node
            for node in self.nodes
            if node.type in {"trigger-webhook", "trigger-plugin", "trigger-schedule"}
        ]
        datasource_entries = [node for node in self.nodes if node.type == "datasource"]
        entries = [*starts, *triggers, *datasource_entries]
        ends = [node for node in self.nodes if node.type == "end"]
        answers = [node for node in self.nodes if node.type == "answer"]
        if self.app_mode == "advanced-chat":
            if len(starts) != 1:
                raise ValueError("chatflow must contain exactly one start node")
            if triggers or datasource_entries:
                raise ValueError("chatflow cannot contain trigger or datasource entry nodes")
            if ends:
                raise ValueError("chatflow cannot contain end nodes")
            if not answers:
                raise ValueError("chatflow must contain at least one answer node")
            entries = starts
        else:
            if not entries:
                raise ValueError("workflow must contain at least one entry node")
            if len(starts) > 1:
                raise ValueError("workflow must contain at most one start node")
            if starts and (triggers or datasource_entries):
                raise ValueError("start node cannot coexist with trigger or datasource entry nodes")
            if datasource_entries and (triggers or len(datasource_entries) > 1):
                raise ValueError("datasource entry cannot coexist with trigger nodes")
            if answers:
                raise ValueError("workflow cannot contain answer nodes")
            if not ends:
                raise ValueError("workflow must contain at least one end node")

        connected = {edge.source for edge in self.edges} | {edge.target for edge in self.edges}
        isolated = [node.id for node in self.nodes if node.id not in connected and len(self.nodes) > 1]
        if isolated:
            raise ValueError(f"workflow contains isolated nodes: {', '.join(isolated)}")

        reachable: set[str] = set()
        for entry in entries:
            reachable.update(_reachable_from(entry.id, self.edges))
        unreachable = [node.id for node in self.nodes if node.id not in reachable]
        if unreachable:
            raise ValueError(f"nodes are not reachable from entry node: {', '.join(unreachable)}")
        return self


def _reachable_from(start_id: str, edges: list[PlanEdge]) -> set[str]:
    graph: dict[str, list[str]] = {}
    for edge in edges:
        graph.setdefault(edge.source, []).append(edge.target)

    seen = {start_id}
    stack = [start_id]
    while stack:
        node_id = stack.pop()
        for target in graph.get(node_id, []):
            if target not in seen:
                seen.add(target)
                stack.append(target)
    return seen


class WorkflowToolSelection(BaseModel):
    provider_id: str = Field(min_length=1)
    provider_type: str = Field(min_length=1)
    tool_name: str = Field(min_length=1)
    provider_name: str | None = None
    tool_label: str | None = None
    description: str | None = None
    parameters: list[dict[str, Any]] = Field(default_factory=list)
    output_schema: dict[str, Any] | None = None
    plugin_id: str | None = None
    plugin_unique_identifier: str | None = None
    tool_parameters: dict[str, Any] = Field(default_factory=dict)
    tool_configurations: dict[str, Any] = Field(default_factory=dict)
    is_team_authorization: bool | None = None
    requires_configuration: bool | None = None


class WorkflowAgentSelection(BaseModel):
    agent_strategy_provider_name: str = Field(min_length=1)
    agent_strategy_name: str = Field(min_length=1)
    agent_strategy_label: str | None = None
    description: str | None = None
    parameters: list[dict[str, Any]] = Field(default_factory=list)
    features: list[str] = Field(default_factory=list)
    output_schema: dict[str, Any] | None = None
    plugin_id: str | None = None
    plugin_unique_identifier: str | None = None
    meta: dict[str, Any] | None = None
    agent_parameters: dict[str, Any] = Field(default_factory=dict)
    requires_configuration: bool | None = None


class WorkflowPlannerSelection(BaseModel):
    provider: Literal["openai", "nvidia"]
    model: str = Field(min_length=1)


class WorkflowTriggerParameter(BaseModel):
    name: str = Field(min_length=1)
    type: Literal[
        "string",
        "number",
        "boolean",
        "object",
        "array[string]",
        "array[number]",
        "array[boolean]",
        "array[object]",
        "file",
    ] = "string"
    required: bool = False


class WorkflowTriggerSelection(BaseModel):
    type: Literal["user-input", "webhook", "schedule", "plugin"] = "user-input"
    method: Literal["GET", "POST", "HEAD", "PATCH", "PUT", "DELETE"] = "POST"
    content_type: Literal[
        "application/json",
        "multipart/form-data",
        "application/x-www-form-urlencoded",
        "text/plain",
        "application/octet-stream",
    ] = "application/json"
    headers: list[WorkflowTriggerParameter] = Field(default_factory=list)
    params: list[WorkflowTriggerParameter] = Field(default_factory=list)
    body: list[WorkflowTriggerParameter] = Field(default_factory=list)
    status_code: int = Field(default=200, ge=100, le=599)
    response_body: str = ""
    timeout: int = Field(default=30, ge=1, le=300)
    mode: Literal["visual", "cron"] = "visual"
    frequency: Literal["hourly", "daily", "weekly", "monthly"] | None = "daily"
    cron_expression: str | None = None
    visual_config: dict[str, Any] | None = Field(
        default_factory=lambda: {
            "time": "09:00 AM",
            "weekdays": ["mon"],
            "on_minute": 0,
            "monthly_days": [1],
        }
    )
    timezone: str = "Asia/Shanghai"
    provider_id: str | None = None
    provider_type: str | None = None
    provider_name: str | None = None
    plugin_id: str | None = None
    plugin_unique_identifier: str | None = None
    event_name: str | None = None
    event_label: str | None = None
    subscription_id: str | None = None
    event_parameters: dict[str, Any] = Field(default_factory=dict)
    parameters_schema: list[dict[str, Any]] = Field(default_factory=list)
    output_schema: dict[str, Any] = Field(default_factory=dict)


class WorkflowRequest(BaseModel):
    message: str = Field(min_length=1)
    app_name: str | None = None
    app_mode: AppMode = "workflow"
    dry_run: bool = False
    dataset_ids: list[str] | None = None
    tool_selections: list[WorkflowToolSelection] | None = None
    agent_selections: list[WorkflowAgentSelection] | None = None
    trigger_selection: WorkflowTriggerSelection | None = None
    planner: WorkflowPlannerSelection | None = None


class WorkflowModifyRequest(BaseModel):
    app_id: str = Field(min_length=1)
    message: str = Field(min_length=1)
    expected_hash: str | None = None
    allow_destructive: bool = False
    plan: WorkflowPlan | None = None
    dataset_ids: list[str] | None = None
    tool_selections: list[WorkflowToolSelection] | None = None
    agent_selections: list[WorkflowAgentSelection] | None = None
    trigger_selection: WorkflowTriggerSelection | None = None
    planner: WorkflowPlannerSelection | None = None


class WorkflowRunDraftRequest(BaseModel):
    app_id: str = Field(min_length=1)
    inputs: dict[str, Any]
    files: list[dict[str, Any]] | None = None
    timeout_seconds: float = Field(default=120, gt=0)


class ChatflowRunDraftRequest(BaseModel):
    app_id: str = Field(min_length=1)
    query: str = Field(min_length=1)
    inputs: dict[str, Any] = Field(default_factory=dict)
    files: list[dict[str, Any]] | None = None
    conversation_id: str | None = None
    parent_message_id: str | None = None
    timeout_seconds: float = Field(default=120, gt=0)


class WorkflowPublishRequest(BaseModel):
    expected_hash: str | None = None
    marked_name: str | None = Field(default=None, max_length=20)
    marked_comment: str | None = Field(default=None, max_length=100)


class WorkflowPublishTaskRequest(WorkflowPublishRequest):
    app_id: str = Field(min_length=1)


class WorkflowTriggerStatusRequest(BaseModel):
    enabled: bool


class ValidationIssue(BaseModel):
    code: str
    message: str
    node_id: str | None = None
    severity: Literal["error", "warning"] = "error"
    path: str | None = None
    suggestion: str | None = None
